import type { ChannelSettings, ChatSettings } from '@maxim/contracts';
import { DUPLICATE_ALLOWED_COUNT_MAX } from './private-control.constants';
import type {
  ChannelSectionKey,
  PrivateSectionKey,
  SettingFieldConfig,
  SettingFieldType,
} from './private-control.types';

export const SECTION_LABELS: Record<PrivateSectionKey, string> = {
  links: 'Модерация ссылок',
  greeting: 'Приветствие',
  profanityFilter: 'Фильтр нецензурной лексики',
  commercialFilter: 'Фильтр коммерческой рекламы',
  duplicates: 'Дубли сообщений',
  limits: 'Ограничения сообщений',
  night: 'Ночной режим',
  extra: 'Дополнительно',
};

export const CHANNEL_SECTION_LABELS: Record<ChannelSectionKey, string> = {
  post_suggestions: 'Предложка',
  comments: 'Обсуждение и реакции',
};

export const CHANNEL_SECTION_FIELDS: Record<
  ChannelSectionKey,
  Array<{
    key: keyof ChannelSettings;
    label: string;
    type: SettingFieldType;
    min?: number;
    max?: number;
  }>
> = {
  post_suggestions: [
    { key: 'postSuggestionsEnabled', label: 'Подсказка «Предложить пост»', type: 'boolean' },
    { key: 'postSuggestionsText', label: 'Требования для участников', type: 'text' },
    { key: 'postSuggestionsButtonEnabled', label: 'Показывать кнопку перехода', type: 'boolean' },
    { key: 'postSuggestionsButtonText', label: 'Название кнопки', type: 'text' },
    { key: 'postSuggestionsButtonUrl', label: 'Ссылка кнопки (из MAX)', type: 'url' },
  ],
  comments: [
    { key: 'commentsEnabled', label: 'Сценарий обсуждения через бота/чат', type: 'boolean' },
    { key: 'commentsModerationEnabled', label: 'Модерация обсуждений ботом', type: 'boolean' },
    { key: 'commentsMessageText', label: 'Текст-подсказка для участников', type: 'text' },
  ],
};

export const SECTION_FIELDS: Record<PrivateSectionKey, SettingFieldConfig[]> = {
  links: [
    {
      key: 'linkPolicy',
      label: 'Режим проверки ссылок',
      type: 'enum',
      enumValues: ['ALERT_ONLY', 'ALLOWLIST_ONLY', 'BLOCKLIST_ONLY'],
    },
    { key: 'linkBotMessageEnabled', label: 'Показывать сообщение бота', type: 'boolean' },
    { key: 'linkBotMessageText', label: 'Текст сообщения бота', type: 'text' },
    { key: 'linkWarnEnabled', label: 'Выдавать предупреждение', type: 'boolean' },
    { key: 'linkWarnMessageText', label: 'Текст предупреждения', type: 'text' },
    { key: 'linkMuteEnabled', label: 'Выдавать мут', type: 'boolean' },
    {
      key: 'linkMuteDurationHours',
      label: 'Срок мута (часы)',
      type: 'number',
      min: 1,
      max: 168,
      step: 1,
      presets: [1, 6, 24, 168],
    },
    { key: 'linkBanEnabled', label: 'Банить нарушителя', type: 'boolean' },
    { key: 'linkBotButtonEnabled', label: 'Показывать кнопку', type: 'boolean' },
    { key: 'linkBotButtonUrl', label: 'Ссылка кнопки', type: 'url' },
    { key: 'linkBotButtonText', label: 'Текст кнопки', type: 'text' },
  ],
  greeting: [
    { key: 'greetingEnabled', label: 'Включить приветствие', type: 'boolean' },
    { key: 'greetingBotMessageEnabled', label: 'Отправлять приветствие', type: 'boolean' },
    {
      key: 'greetingDeleteBotMessageEnabled',
      label: 'Удалять приветствие',
      type: 'boolean',
    },
    {
      key: 'greetingDeleteBotMessageDelayMinutes',
      label: 'Задержка удаления приветствия',
      type: 'number',
      min: 0.5,
      max: 60,
      step: 1,
      presets: [0.5, 1, 5],
    },
    { key: 'greetingBotMessageText', label: 'Текст приветствия', type: 'text' },
    { key: 'greetingBotButtonEnabled', label: 'Показывать кнопку', type: 'boolean' },
    { key: 'greetingBotButtonUrl', label: 'Ссылка кнопки', type: 'url' },
    { key: 'greetingBotButtonText', label: 'Текст кнопки', type: 'text' },
    {
      key: 'greetingRulesButtonEnabled',
      label: 'Показывать кнопку правил',
      type: 'boolean',
    },
  ],
  profanityFilter: [
    { key: 'russianProfanityFilterEnabled', label: 'Включить фильтр', type: 'boolean' },
    { key: 'profanityBotMessageEnabled', label: 'Показывать сообщение бота', type: 'boolean' },
    { key: 'profanityWarnEnabled', label: 'Выдавать предупреждение', type: 'boolean' },
    { key: 'profanityMuteEnabled', label: 'Выдавать мут', type: 'boolean' },
    {
      key: 'profanityMuteDurationHours',
      label: 'Срок мута (часы)',
      type: 'number',
      min: 1,
      max: 168,
      step: 1,
      presets: [1, 6, 24, 168],
    },
    { key: 'profanityBanEnabled', label: 'Банить нарушителя', type: 'boolean' },
  ],
  commercialFilter: [
    { key: 'commercialAdsFilterEnabled', label: 'Включить фильтр', type: 'boolean' },
    {
      key: 'commercialAdsSensitivity',
      label: 'Уровень строгости',
      type: 'enum',
      enumValues: ['BALANCED', 'STRICT'],
    },
    {
      key: 'commercialAdsWarnThreshold',
      label: 'Порог предупреждения',
      type: 'number',
      min: 1,
      max: 100,
      step: 5,
      presets: [20, 40, 60],
    },
    {
      key: 'commercialAdsDeleteThreshold',
      label: 'Порог удаления',
      type: 'number',
      min: 1,
      max: 100,
      step: 5,
      presets: [40, 60, 80],
    },
    { key: 'textFiltersBotMessageEnabled', label: 'Показывать сообщение бота', type: 'boolean' },
    { key: 'textFiltersBotMessageText', label: 'Текст сообщения бота', type: 'text' },
    { key: 'textFiltersWarnEnabled', label: 'Выдавать предупреждение', type: 'boolean' },
    { key: 'textFiltersWarnMessageText', label: 'Текст предупреждения', type: 'text' },
    { key: 'textFiltersMuteEnabled', label: 'Выдавать мут', type: 'boolean' },
    {
      key: 'textFiltersMuteDurationHours',
      label: 'Срок мута (часы)',
      type: 'number',
      min: 1,
      max: 168,
      step: 1,
      presets: [1, 6, 24, 168],
    },
    { key: 'textFiltersBanEnabled', label: 'Банить нарушителя', type: 'boolean' },
    { key: 'textFiltersBotButtonEnabled', label: 'Показывать кнопку', type: 'boolean' },
    { key: 'textFiltersBotButtonUrl', label: 'Ссылка кнопки', type: 'url' },
    { key: 'textFiltersBotButtonText', label: 'Текст кнопки', type: 'text' },
  ],
  duplicates: [
    { key: 'antiDuplicateEnabled', label: 'Включить антидубли', type: 'boolean' },
    { key: 'duplicateBotMessageEnabled', label: 'Шаг 1: объяснение', type: 'boolean' },
    { key: 'duplicateWarnEnabled', label: 'Шаг 2: предупреждение', type: 'boolean' },
    { key: 'duplicateMuteEnabled', label: 'Шаг 3: мут', type: 'boolean' },
    {
      key: 'duplicateMuteDurationHours',
      label: 'Срок мута (часы)',
      type: 'number',
      min: 1,
      max: 168,
      step: 1,
      presets: [1, 6, 24, 168],
    },
    { key: 'duplicateBanEnabled', label: 'Шаг 4: бан', type: 'boolean' },
    {
      key: 'duplicateWarnWindowSec',
      label: 'Окно дублей (сек)',
      type: 'number',
      min: 3600,
      max: 604800,
      step: 3600,
      presets: [3600, 21600, 86400],
    },
    {
      key: 'duplicateWarnMaxCount',
      label: 'Разрешено дублей',
      type: 'number',
      min: 0,
      max: DUPLICATE_ALLOWED_COUNT_MAX,
      step: 1,
      presets: [0, 1, 3, 5],
    },
    { key: 'duplicateBotMessageText', label: 'Текст сообщения бота', type: 'text' },
    { key: 'duplicateBotButtonEnabled', label: 'Показывать кнопку', type: 'boolean' },
    { key: 'duplicateBotButtonUrl', label: 'Ссылка кнопки', type: 'url' },
    { key: 'duplicateBotButtonText', label: 'Текст кнопки', type: 'text' },
  ],
  limits: [
    { key: 'antiSpamEnabled', label: 'Включить антиспам', type: 'boolean' },
    { key: 'messageCountLimitEnabled', label: 'Лимит сообщений', type: 'boolean' },
    {
      key: 'messageCountLimitMessages',
      label: 'Сообщений за окно',
      type: 'number',
      min: 1,
      max: 10,
      step: 1,
      presets: [1, 3, 5],
    },
    {
      key: 'messageCountLimitWindowHours',
      label: 'Окно лимита (часы)',
      type: 'number',
      min: 1,
      max: 24,
      step: 1,
      presets: [1, 6, 24],
    },
    { key: 'maxMessageLengthEnabled', label: 'Ограничить длину сообщений', type: 'boolean' },
    {
      key: 'maxMessageLength',
      label: 'Макс. длина сообщения',
      type: 'number',
      min: 50,
      max: 10000,
      step: 50,
      presets: [300, 800, 1500],
    },
    { key: 'photoMessageCooldownEnabled', label: 'Ограничить частые фото', type: 'boolean' },
    {
      key: 'photoMessageCooldownHours',
      label: 'Интервал между фото (часы)',
      type: 'number',
      min: 1,
      max: 336,
      step: 1,
      presets: [1, 6, 24],
    },
    { key: 'stickerMessageCooldownEnabled', label: 'Ограничить частые стикеры', type: 'boolean' },
    {
      key: 'stickerMessageCooldownMinutes',
      label: 'Интервал между стикерами (мин)',
      type: 'number',
      min: 1,
      max: 1440,
      step: 5,
      presets: [5, 15, 60],
    },
    { key: 'photoMessagesEnabled', label: 'Разрешить фото', type: 'boolean' },
    { key: 'videoMessagesEnabled', label: 'Разрешить видео', type: 'boolean' },
    { key: 'fileMessagesEnabled', label: 'Разрешить файлы', type: 'boolean' },
    { key: 'voiceMessagesEnabled', label: 'Разрешить голосовые', type: 'boolean' },
    { key: 'phoneNumbersEnabled', label: 'Разрешить телефоны', type: 'boolean' },
    { key: 'messageLimitsBlockedWords', label: 'Стоп-слова', type: 'text' },
    { key: 'messageLimitsBlockedDomains', label: 'Запрещенные домены', type: 'text' },
    { key: 'messageLimitsBotMessageEnabled', label: 'Показывать сообщение бота', type: 'boolean' },
    { key: 'messageLimitsBotMessageText', label: 'Текст сообщения бота', type: 'text' },
    { key: 'messageLimitsWarnEnabled', label: 'Штраф: предупреждение', type: 'boolean' },
    { key: 'messageLimitsWarnMessageText', label: 'Текст предупреждения', type: 'text' },
    { key: 'messageLimitsMuteEnabled', label: 'Штраф: мут', type: 'boolean' },
    {
      key: 'messageLimitsMuteDurationHours',
      label: 'Срок мута (часы)',
      type: 'number',
      min: 1,
      max: 168,
      step: 1,
      presets: [1, 6, 24, 168],
    },
    { key: 'messageLimitsBanEnabled', label: 'Штраф: бан', type: 'boolean' },
    { key: 'messageLimitsBotButtonEnabled', label: 'Показывать кнопку', type: 'boolean' },
    { key: 'messageLimitsBotButtonUrl', label: 'Ссылка кнопки', type: 'url' },
    { key: 'messageLimitsBotButtonText', label: 'Текст кнопки', type: 'text' },
  ],
  night: [
    { key: 'nightModeEnabled', label: 'Включить ночной режим', type: 'boolean' },
    { key: 'nightModeStartTimeMinutes', label: 'Начало (HH:MM)', type: 'time' },
    { key: 'nightModeEndTimeMinutes', label: 'Конец (HH:MM)', type: 'time' },
    { key: 'nightModeTimezone', label: 'Часовой пояс', type: 'timezone' },
    { key: 'nightModeBotMessageEnabled', label: 'Показывать сообщение бота', type: 'boolean' },
    { key: 'nightModeBotMessageText', label: 'Текст сообщения бота', type: 'text' },
    { key: 'nightModeCommentsEnabled', label: 'Показывать кнопку комментариев', type: 'boolean' },
    {
      key: 'nightModeOpenMessageEnabled',
      label: 'Показывать сообщение об открытии',
      type: 'boolean',
    },
    { key: 'nightModeOpenMessageText', label: 'Текст сообщения об открытии', type: 'text' },
    { key: 'nightModeBotButtonEnabled', label: 'Показывать кнопку', type: 'boolean' },
    { key: 'nightModeBotButtonUrl', label: 'Ссылка кнопки', type: 'url' },
    { key: 'nightModeBotButtonText', label: 'Текст кнопки', type: 'text' },
    { key: 'nightModeRulesButtonEnabled', label: 'Показывать кнопку правил', type: 'boolean' },
    { key: 'nightModeForceCloseEnabled', label: 'Закрыть группу вручную', type: 'boolean' },
    { key: 'nightModeForceCloseForever', label: 'Держать закрытой бессрочно', type: 'boolean' },
    { key: 'nightModeForceCloseHours', label: 'Часы ручного закрытия', type: 'number' },
    { key: 'nightModeForceCloseDays', label: 'Дни ручного закрытия', type: 'number' },
  ],
  extra: [
    { key: 'deleteSpammersEnabled', label: 'Удалять спамеров', type: 'boolean' },
    { key: 'deleteBotMessagesEnabled', label: 'Удалять сообщения бота', type: 'boolean' },
    {
      key: 'deleteBotMessagesDelayMinutes',
      label: 'Задержка удаления',
      type: 'number',
      min: 0.5,
      max: 60,
      step: 1,
      presets: [0.5, 1, 5],
    },
    { key: 'removeBotsFromGroupEnabled', label: 'Удалять ботов из чата', type: 'boolean' },
  ],
};

export const SECTION_SETTING_KEYS: Record<PrivateSectionKey, readonly (keyof ChatSettings)[]> = {
  links: SECTION_FIELDS.links.map((field) => field.key),
  greeting: SECTION_FIELDS.greeting.map((field) => field.key),
  profanityFilter: SECTION_FIELDS.profanityFilter.map((field) => field.key),
  commercialFilter: SECTION_FIELDS.commercialFilter.map((field) => field.key),
  duplicates: SECTION_FIELDS.duplicates.map((field) => field.key),
  limits: SECTION_FIELDS.limits.map((field) => field.key),
  night: SECTION_FIELDS.night.map((field) => field.key),
  extra: SECTION_FIELDS.extra.map((field) => field.key),
};

export const SECTION_ORDER: PrivateSectionKey[] = [
  'links',
  'greeting',
  'profanityFilter',
  'commercialFilter',
  'duplicates',
  'limits',
  'night',
  'extra',
];

export const SECTION_CARD_FIELDS: Record<
  PrivateSectionKey,
  { basic: readonly (keyof ChatSettings)[]; advanced: readonly (keyof ChatSettings)[] }
> = {
  links: {
    basic: [
      'linkPolicy',
      'linkWarnEnabled',
      'linkMuteEnabled',
      'linkMuteDurationHours',
      'linkBanEnabled',
      'linkBotMessageEnabled',
    ],
    advanced: [
      'linkBotMessageText',
      'linkWarnMessageText',
      'linkBotButtonEnabled',
      'linkBotButtonText',
      'linkBotButtonUrl',
    ],
  },
  greeting: {
    basic: [
      'greetingEnabled',
      'greetingBotMessageEnabled',
      'greetingDeleteBotMessageEnabled',
      'greetingDeleteBotMessageDelayMinutes',
    ],
    advanced: [
      'greetingBotMessageText',
      'greetingBotButtonEnabled',
      'greetingBotButtonText',
      'greetingBotButtonUrl',
      'greetingRulesButtonEnabled',
    ],
  },
  profanityFilter: {
    basic: [
      'russianProfanityFilterEnabled',
      'profanityWarnEnabled',
      'profanityMuteEnabled',
      'profanityMuteDurationHours',
      'profanityBanEnabled',
    ],
    advanced: ['profanityBotMessageEnabled'],
  },
  commercialFilter: {
    basic: [
      'commercialAdsFilterEnabled',
      'commercialAdsSensitivity',
      'commercialAdsWarnThreshold',
      'commercialAdsDeleteThreshold',
    ],
    advanced: [
      'textFiltersBotMessageEnabled',
      'textFiltersBotMessageText',
      'textFiltersWarnEnabled',
      'textFiltersWarnMessageText',
      'textFiltersMuteEnabled',
      'textFiltersMuteDurationHours',
      'textFiltersBanEnabled',
      'textFiltersBotButtonEnabled',
      'textFiltersBotButtonText',
      'textFiltersBotButtonUrl',
    ],
  },
  duplicates: {
    basic: [
      'antiDuplicateEnabled',
      'duplicateBotMessageEnabled',
      'duplicateWarnEnabled',
      'duplicateMuteEnabled',
      'duplicateMuteDurationHours',
      'duplicateBanEnabled',
    ],
    advanced: [
      'duplicateWarnWindowSec',
      'duplicateWarnMaxCount',
      'duplicateBotMessageText',
      'duplicateBotButtonEnabled',
      'duplicateBotButtonText',
      'duplicateBotButtonUrl',
    ],
  },
  limits: {
    basic: [
      'antiSpamEnabled',
      'messageCountLimitEnabled',
      'messageCountLimitMessages',
      'messageCountLimitWindowHours',
      'maxMessageLengthEnabled',
      'maxMessageLength',
      'photoMessagesEnabled',
      'videoMessagesEnabled',
      'fileMessagesEnabled',
      'voiceMessagesEnabled',
      'phoneNumbersEnabled',
      'messageLimitsBlockedWords',
      'messageLimitsBlockedDomains',
    ],
    advanced: [
      'photoMessageCooldownEnabled',
      'photoMessageCooldownHours',
      'stickerMessageCooldownEnabled',
      'stickerMessageCooldownMinutes',
      'messageLimitsBotMessageEnabled',
      'messageLimitsBotMessageText',
      'messageLimitsWarnEnabled',
      'messageLimitsWarnMessageText',
      'messageLimitsMuteEnabled',
      'messageLimitsMuteDurationHours',
      'messageLimitsBanEnabled',
      'messageLimitsBotButtonEnabled',
      'messageLimitsBotButtonText',
      'messageLimitsBotButtonUrl',
    ],
  },
  night: {
    basic: [
      'nightModeEnabled',
      'nightModeStartTimeMinutes',
      'nightModeEndTimeMinutes',
      'nightModeTimezone',
    ],
    advanced: [
      'nightModeBotMessageEnabled',
      'nightModeBotMessageText',
      'nightModeBotButtonEnabled',
      'nightModeBotButtonText',
      'nightModeBotButtonUrl',
      'nightModeForceCloseEnabled',
      'nightModeForceCloseForever',
      'nightModeForceCloseHours',
      'nightModeForceCloseDays',
    ],
  },
  extra: {
    basic: [
      'deleteSpammersEnabled',
      'deleteBotMessagesEnabled',
      'deleteBotMessagesDelayMinutes',
      'removeBotsFromGroupEnabled',
    ],
    advanced: [],
  },
};
