type VariantFamily = {
  stems: readonly string[];
  suffixes: readonly string[];
  exact?: readonly string[];
};

const CYRILLIC_HARD_MASC_SUFFIXES = ['', 'а', 'у', 'е', 'ом', 'и', 'ов', 'ам', 'ами', 'ах'];
const CYRILLIC_FEM_A_SUFFIXES = ['а', 'и', 'е', 'у', 'ой', 'ою', 'ам', 'ами', 'ах'];
const CYRILLIC_SOFT_FEM_SUFFIXES = ['ь', 'и', 'ью', 'ей', 'ям', 'ями', 'ях'];
const CYRILLIC_ADJECTIVE_SUFFIXES = [
  'ий',
  'ая',
  'ое',
  'ие',
  'ого',
  'ому',
  'ую',
  'ым',
  'ых',
  'ыми',
];
const CYRILLIC_HARD_ADJECTIVE_SUFFIXES = [
  'ый',
  'ая',
  'ое',
  'ые',
  'ого',
  'ому',
  'ую',
  'ым',
  'ых',
  'ыми',
];
const CYRILLIC_OK_SUFFIXES = ['ок', 'ка', 'ку', 'ке', 'ком', 'ки', 'ков', 'кам', 'ками', 'ках'];
const CYRILLIC_EC_SUFFIXES = ['ец', 'ца', 'цу', 'це', 'цем', 'цы', 'цев', 'цам', 'цами', 'цах'];
const CYRILLIC_UK_SUFFIXES = ['к', 'ка', 'ку', 'ке', 'ком', 'ки', 'ков', 'кам', 'ками', 'ках'];
const LATIN_HARD_MASC_SUFFIXES = ['', 'a', 'u', 'e', 'om', 'i', 'ov', 'am', 'ami', 'ah'];
const LATIN_FEM_A_SUFFIXES = ['a', 'i', 'e', 'u', 'oy', 'oyu', 'am', 'ami', 'ah'];
const LATIN_OK_SUFFIXES = ['ok', 'ka', 'ku', 'ke', 'kom', 'ki', 'kov', 'kam', 'kami', 'kah'];

function buildVariantSet(families: readonly VariantFamily[]): Set<string> {
  const variants = new Set<string>();

  for (const family of families) {
    for (const exact of family.exact ?? []) {
      if (exact) {
        variants.add(exact);
      }
    }

    for (const stem of family.stems) {
      for (const suffix of family.suffixes) {
        const variant = `${stem}${suffix}`;
        if (variant) {
          variants.add(variant);
        }
      }
    }
  }

  return variants;
}

const PROFANITY_VARIANT_FAMILIES: readonly VariantFamily[] = [
  {
    stems: ['сук'],
    suffixes: CYRILLIC_FEM_A_SUFFIXES,
    exact: ['сукин', 'сукина', 'сукину', 'сукины', 'сукиным', 'сукину', 'сукино', 'сукины'],
  },
  {
    stems: ['сцук'],
    suffixes: CYRILLIC_FEM_A_SUFFIXES,
    exact: ['сцука', 'сцуки', 'сцуке', 'сцуку', 'сцукой', 'сцукою', 'сцукам', 'сцуками'],
  },
  {
    stems: ['суч'],
    suffixes: [
      'ка',
      'ки',
      'ке',
      'ку',
      'кой',
      'кою',
      'ек',
      'кам',
      'ками',
      'ках',
      'ара',
      'ары',
      'аре',
      'ару',
      'арой',
      'арою',
      'онок',
      'онка',
      'онку',
      'онки',
    ],
  },
  {
    stems: ['мраз'],
    suffixes: CYRILLIC_SOFT_FEM_SUFFIXES,
    exact: [
      'мразота',
      'мразоты',
      'мразоте',
      'мразоту',
      'мразотой',
      'мразотою',
      'мразотам',
      'мразотами',
      'мразотах',
      'мразина',
      'мразины',
      'мразину',
      'мразиной',
    ],
  },
  {
    stems: ['шлюх'],
    suffixes: CYRILLIC_FEM_A_SUFFIXES,
    exact: ['шлюшка', 'шлюшки', 'шлюшке', 'шлюшку', 'шлюшкой', 'шлюшками', 'шлюшках'],
  },
  {
    stems: ['шлух'],
    suffixes: CYRILLIC_FEM_A_SUFFIXES,
    exact: ['шлушка', 'шлушки', 'шлушке', 'шлушку', 'шлушкой'],
  },
  {
    stems: ['мудак'],
    suffixes: CYRILLIC_HARD_MASC_SUFFIXES,
    exact: [
      'мудацкий',
      'мудацкая',
      'мудацкое',
      'мудацкие',
      'мудацкого',
      'мудацкому',
      'мудацкую',
      'мудацким',
      'мудацких',
      'мудачье',
      'мудачья',
      'мудачью',
      'мудачьем',
    ],
  },
  {
    stems: ['мудачин'],
    suffixes: CYRILLIC_FEM_A_SUFFIXES,
  },
  {
    stems: ['мудаг'],
    suffixes: CYRILLIC_HARD_MASC_SUFFIXES,
    exact: ['мудажье', 'мудажья', 'мудажью', 'мудажьем'],
  },
  {
    stems: ['мудил'],
    suffixes: CYRILLIC_HARD_MASC_SUFFIXES,
    exact: ['мудила', 'мудилы', 'мудиле', 'мудилу', 'мудилой', 'мудилою', 'мудилам', 'мудилами'],
  },
  {
    stems: ['дибил'],
    suffixes: CYRILLIC_HARD_MASC_SUFFIXES,
    exact: [
      'дибилка',
      'дибилки',
      'дибилке',
      'дибилку',
      'дибилкой',
      'дибильный',
      'дибильная',
      'дибильное',
      'дибильные',
      'дибильного',
      'дибильному',
      'дибильную',
      'дибильным',
      'дибильных',
    ],
  },
  {
    stems: ['долбоеб'],
    suffixes: CYRILLIC_HARD_MASC_SUFFIXES,
    exact: [
      'долбоебка',
      'долбоебки',
      'долбоебке',
      'долбоебку',
      'долбоебкой',
      'долбоебство',
      'долбоебский',
      'долбоебская',
      'долбоебское',
      'долбоебские',
    ],
  },
  {
    stems: ['далбаеб', 'далбоеб', 'долбаеп', 'далбаеп'],
    suffixes: CYRILLIC_HARD_MASC_SUFFIXES,
    exact: [
      'далбаебка',
      'далбаебки',
      'далбаебке',
      'далбаебку',
      'далбаепка',
      'далбаепки',
      'долбаепка',
      'долбаепки',
      'далбоебка',
      'далбоебки',
    ],
  },
  {
    stems: ['ублюд'],
    suffixes: CYRILLIC_OK_SUFFIXES,
    exact: [
      'ублюдочный',
      'ублюдочная',
      'ублюдочное',
      'ублюдочные',
      'ублюдочного',
      'ублюдочному',
      'ублюдочную',
      'ублюдочным',
      'ублюдочных',
    ],
  },
  {
    stems: ['ублют'],
    suffixes: CYRILLIC_OK_SUFFIXES,
    exact: ['ублюток', 'ублютка', 'ублютку', 'ублютке', 'ублютки', 'ублютков'],
  },
  {
    stems: ['твар'],
    suffixes: CYRILLIC_SOFT_FEM_SUFFIXES,
    exact: [
      'тварина',
      'тварины',
      'тварине',
      'тварину',
      'твариной',
      'твариною',
      'тварюга',
      'тварюги',
      'тварюге',
      'тварюгу',
      'тварюгой',
    ],
  },
  {
    stems: ['дебил'],
    suffixes: CYRILLIC_HARD_MASC_SUFFIXES,
    exact: [
      'дебилка',
      'дебилки',
      'дебилке',
      'дебилку',
      'дебилкой',
      'дебильный',
      'дебильная',
      'дебильное',
      'дебильные',
      'дебильного',
      'дебильному',
      'дебильную',
      'дебильным',
      'дебильных',
      'дебилоид',
      'дебилоиды',
      'дебилоида',
      'дебилоиду',
      'дебилизм',
      'дебилизма',
      'дебилизму',
      'дебилизме',
      'дебилизмы',
      'дебилизмом',
    ],
  },
  {
    stems: ['идиот'],
    suffixes: CYRILLIC_HARD_MASC_SUFFIXES,
    exact: [
      'идиотка',
      'идиотки',
      'идиотке',
      'идиотку',
      'идиоткой',
      'идиотизм',
      'идиотизма',
      'идиотизму',
      'идиотизме',
      'идиотизмом',
      'идиотский',
      'идиотская',
      'идиотское',
      'идиотские',
      'идиотского',
      'идиотскому',
      'идиотскую',
      'идиотским',
      'идиотских',
    ],
  },
  {
    stems: ['урод'],
    suffixes: CYRILLIC_HARD_MASC_SUFFIXES,
    exact: [
      'уродка',
      'уродки',
      'уродке',
      'уродку',
      'уродкой',
      'уродина',
      'уродины',
      'уродине',
      'уродину',
      'уродиной',
      'уродский',
      'уродская',
      'уродское',
      'уродские',
      'уродского',
      'уродскому',
      'уродскую',
      'уродским',
      'уродских',
    ],
  },
  {
    stems: ['гандон'],
    suffixes: CYRILLIC_HARD_MASC_SUFFIXES,
    exact: [
      'гандонище',
      'гандонища',
      'гандонищу',
      'гандонищем',
      'гандонский',
      'гандонская',
      'гандонское',
      'гандонские',
      'гандонского',
    ],
  },
  {
    stems: ['пидор'],
    suffixes: CYRILLIC_HARD_MASC_SUFFIXES,
    exact: [
      'пидорский',
      'пидорская',
      'пидорское',
      'пидорские',
      'пидорского',
      'пидорскому',
      'пидорскую',
      'пидорским',
      'пидорских',
      'пидрила',
      'пидрилы',
      'пидриле',
      'пидрилу',
      'пидрилой',
      'пидрильник',
      'пидрильника',
      'пидрильнику',
      'пидорок',
      'пидорка',
      'пидорку',
      'пидорки',
    ],
  },
  {
    stems: ['пидорнут', 'пидарнут'],
    suffixes: CYRILLIC_HARD_ADJECTIVE_SUFFIXES,
  },
  {
    stems: ['пидорас'],
    suffixes: CYRILLIC_HARD_MASC_SUFFIXES,
    exact: [
      'пидарас',
      'пидарасы',
      'пидараса',
      'пидарасу',
      'пидарасом',
      'пидарасами',
      'пидорасина',
      'пидорасины',
      'пидорасине',
      'пидорасину',
      'пидорасиной',
    ],
  },
  {
    stems: ['педор', 'педар'],
    suffixes: CYRILLIC_HARD_MASC_SUFFIXES,
    exact: [
      'педорский',
      'педорская',
      'педорское',
      'педорские',
      'педорского',
      'педорскому',
      'педорскую',
      'педорским',
      'педорских',
      'педарский',
      'педарская',
      'педарское',
      'педарские',
    ],
  },
  {
    stems: ['педик'],
    suffixes: CYRILLIC_HARD_MASC_SUFFIXES,
    exact: [
      'педрила',
      'педрилы',
      'педриле',
      'педрилу',
      'педрилой',
      'педрило',
      'педрилы',
      'педрильник',
      'педрильника',
    ],
  },
  {
    stems: ['гнид'],
    suffixes: CYRILLIC_FEM_A_SUFFIXES,
    exact: ['гнилушка', 'гнилушки', 'гнилушке', 'гнилушку', 'гнилушкой', 'гнидина', 'гнидины'],
  },
  {
    stems: ['сволоч'],
    suffixes: CYRILLIC_SOFT_FEM_SUFFIXES,
    exact: [
      'сволота',
      'сволоты',
      'сволоте',
      'сволоту',
      'сволотой',
      'сволотою',
      'сволочуга',
      'сволочуги',
      'сволочуге',
      'сволочугу',
    ],
  },
  {
    stems: ['паскуд'],
    suffixes: CYRILLIC_FEM_A_SUFFIXES,
    exact: [
      'паскудный',
      'паскудная',
      'паскудное',
      'паскудные',
      'паскудного',
      'паскудному',
      'паскудную',
      'паскудным',
      'паскудных',
      'паскудина',
      'паскудины',
      'паскудину',
    ],
  },
  {
    stems: ['подон'],
    suffixes: CYRILLIC_OK_SUFFIXES,
    exact: [
      'подоночный',
      'подоночная',
      'подоночное',
      'подоночные',
      'подоночного',
      'подоночному',
      'подоночную',
      'подоночным',
      'подоночных',
    ],
  },
  {
    stems: ['мерзав'],
    suffixes: CYRILLIC_EC_SUFFIXES,
    exact: [
      'мерзавка',
      'мерзавки',
      'мерзавке',
      'мерзавку',
      'мерзавкой',
      'мерзавский',
      'мерзавская',
      'мерзавское',
      'мерзавские',
      'мерзавского',
      'мерзавскому',
      'мерзавскую',
    ],
  },
  {
    stems: ['придур'],
    suffixes: CYRILLIC_OK_SUFFIXES,
    exact: [
      'придурочный',
      'придурочная',
      'придурочное',
      'придурочные',
      'придурочного',
      'придурочному',
      'придурочную',
      'придурочным',
      'придурочных',
      'придурь',
      'придури',
      'придурьи',
    ],
  },
  {
    stems: ['кретин'],
    suffixes: CYRILLIC_HARD_MASC_SUFFIXES,
    exact: [
      'кретинка',
      'кретинки',
      'кретинке',
      'кретинку',
      'кретинкой',
      'кретинский',
      'кретинская',
      'кретинское',
      'кретинские',
      'кретинского',
      'кретинскому',
      'кретинскую',
      'кретинским',
      'кретинских',
    ],
  },
  {
    stems: ['имбецил'],
    suffixes: CYRILLIC_HARD_MASC_SUFFIXES,
    exact: [
      'имбецилка',
      'имбецилки',
      'имбецилке',
      'имбецилку',
      'имбецилкой',
      'имбецильный',
      'имбецильная',
      'имбецильное',
      'имбецильные',
      'имбецильного',
      'имбецильному',
      'имбецильную',
      'имбецильным',
      'имбецильных',
    ],
  },
  {
    stems: ['скотин'],
    suffixes: CYRILLIC_FEM_A_SUFFIXES,
    exact: [
      'скотинам',
      'скотинами',
      'скотинах',
      'скотский',
      'скотская',
      'скотское',
      'скотские',
      'скотского',
      'скотскому',
      'скотскую',
      'скотским',
      'скотских',
    ],
  },
  {
    stems: ['чмошн'],
    suffixes: CYRILLIC_ADJECTIVE_SUFFIXES,
    exact: ['чмо', 'чмырь', 'чмыря', 'чмырю', 'чмырем', 'чмошник', 'чмошника', 'чмошнику'],
  },
  {
    stems: ['говню'],
    suffixes: CYRILLIC_UK_SUFFIXES,
    exact: [
      'говно',
      'говна',
      'говну',
      'говном',
      'говне',
      'говнище',
      'говнища',
      'говнищу',
      'говнищем',
      'говенный',
      'говенная',
      'говенное',
      'говенные',
      'говенного',
      'говенному',
      'говенную',
      'говенным',
      'говенных',
    ],
  },
  {
    stems: ['дерьмов'],
    suffixes: CYRILLIC_ADJECTIVE_SUFFIXES,
    exact: [
      'дерьмо',
      'дерьма',
      'дерьму',
      'дерьмом',
      'дерьме',
      'дерьмище',
      'дерьмища',
      'дерьмищу',
      'дерьмищем',
      'дерьмово',
      'дерьмовый',
      'дерьмовая',
      'дерьмовые',
      'дерьмового',
    ],
  },
  {
    stems: ['pidor'],
    suffixes: LATIN_HARD_MASC_SUFFIXES,
    exact: ['pidoras', 'pidorasy', 'pidorasa', 'pidorasu', 'pidorom', 'pidrila', 'pidrilu'],
  },
  {
    stems: ['mudak'],
    suffixes: LATIN_HARD_MASC_SUFFIXES,
    exact: ['mudachyo', 'mudatskiy', 'mudatskaya', 'mudatskoe', 'mudatskie'],
  },
  {
    stems: ['debil'],
    suffixes: LATIN_HARD_MASC_SUFFIXES,
    exact: ['debilka', 'debilki', 'debilku', 'debilnuy', 'debilnyy', 'debilnaya', 'debilnoe'],
  },
  {
    stems: ['idiot'],
    suffixes: LATIN_HARD_MASC_SUFFIXES,
    exact: ['idiotka', 'idiotki', 'idiotku', 'idiotskiy', 'idiotskaya', 'idiotskoe'],
  },
  {
    stems: ['urod'],
    suffixes: LATIN_HARD_MASC_SUFFIXES,
    exact: ['urodina', 'urodiny', 'urodinu', 'urodskiy', 'urodskaya', 'urodskoe'],
  },
  {
    stems: ['suk'],
    suffixes: LATIN_FEM_A_SUFFIXES,
    exact: ['suchka', 'suchki', 'suchku', 'suchkoy', 'suchara', 'sucharu', 'suchonok'],
  },
  {
    stems: ['scuk'],
    suffixes: LATIN_FEM_A_SUFFIXES,
    exact: ['scuka', 'scuki', 'scuke', 'scuku', 'scukoy', 'scukami'],
  },
  {
    stems: ['mraz'],
    suffixes: ['', 'i', 'yu', 'ey', 'yam', 'yami', 'yah'],
    exact: ['mrazota', 'mrazoty', 'mrazotu', 'mrazina', 'mrazinu'],
  },
  {
    stems: ['shlyuh'],
    suffixes: LATIN_FEM_A_SUFFIXES,
    exact: ['shlyushka', 'shlyushki', 'shlyushku', 'shlyushkoy'],
  },
  {
    stems: ['shluh'],
    suffixes: LATIN_FEM_A_SUFFIXES,
    exact: ['shluka', 'shluki', 'shluku', 'shlukoy'],
  },
  {
    stems: ['gandon'],
    suffixes: LATIN_HARD_MASC_SUFFIXES,
    exact: ['gandonishche', 'gandonam', 'gandonami'],
  },
  {
    stems: ['ublyud'],
    suffixes: LATIN_OK_SUFFIXES,
    exact: ['ublyudochnyy', 'ublyudochnaya', 'ublyudochnoe'],
  },
  {
    stems: ['ublyut'],
    suffixes: LATIN_OK_SUFFIXES,
    exact: ['ublyutok', 'ublyutka', 'ublyutku', 'ublyutke'],
  },
  {
    stems: ['dibil'],
    suffixes: LATIN_HARD_MASC_SUFFIXES,
    exact: ['dibilka', 'dibilki', 'dibilku', 'dibilnyy', 'dibilnaya', 'dibilnoe'],
  },
  {
    stems: ['mudag'],
    suffixes: LATIN_HARD_MASC_SUFFIXES,
    exact: ['mudazhyo', 'mudazhya', 'mudazhyu', 'mudazhyem'],
  },
  {
    stems: ['dalbaeb', 'dalboeb', 'dolbaep', 'dalbaep'],
    suffixes: LATIN_HARD_MASC_SUFFIXES,
    exact: ['dalbaebka', 'dalboebka', 'dolbaepka', 'dalbaepka'],
  },
  {
    stems: ['pedor', 'pedar'],
    suffixes: LATIN_HARD_MASC_SUFFIXES,
    exact: ['pedorskiy', 'pedorskaya', 'pedarskiy', 'pedarskaya'],
  },
];

const EXACT_PROFANITY_VARIANTS = buildVariantSet(PROFANITY_VARIANT_FAMILIES);

export const PROFANITY_EXACT_VARIANT_COUNT = EXACT_PROFANITY_VARIANTS.size;

export function isExactProfanityVariant(value: string): boolean {
  return EXACT_PROFANITY_VARIANTS.has(value);
}
