type VariantFamily = {
  stems: readonly string[];
  suffixes: readonly string[];
  exact?: readonly string[];
};

const CYRILLIC_HARD_MASC_SUFFIXES = ['', 'а', 'у', 'е', 'ом', 'и', 'ов', 'ам', 'ами', 'ах'];
const CYRILLIC_FEM_A_SUFFIXES = ['а', 'и', 'е', 'у', 'ой', 'ою', 'ам', 'ами', 'ах'];
const CYRILLIC_HARD_FEM_A_SUFFIXES = ['а', 'ы', 'е', 'у', 'ой', 'ою', 'ам', 'ами', 'ах'];
const CYRILLIC_FEM_YA_SUFFIXES = ['я', 'и', 'е', 'ю', 'ей', 'ею', 'ям', 'ями', 'ях'];
const CYRILLIC_SOFT_FEM_SUFFIXES = ['ь', 'и', 'ью', 'ей', 'ям', 'ями', 'ях'];
const CYRILLIC_ADJECTIVE_SUFFIXES = ['ий', 'ая', 'ое', 'ие', 'ого', 'ому', 'ую', 'ым', 'ых', 'ыми'];
const CYRILLIC_HARD_ADJECTIVE_SUFFIXES = [
  'ый',
  'ая',
  'ое',
  'ые',
  'ого',
  'ому',
  'ую',
  'ым',
  'ых',
  'ыми',
];
const CYRILLIC_OK_SUFFIXES = ['ок', 'ка', 'ку', 'ке', 'ком', 'ки', 'ков', 'кам', 'ками', 'ках'];
const CYRILLIC_EC_SUFFIXES = ['ец', 'ца', 'цу', 'це', 'цем', 'цы', 'цев', 'цам', 'цами', 'цах'];
const CYRILLIC_UK_SUFFIXES = ['к', 'ка', 'ку', 'ке', 'ком', 'ки', 'ков', 'кам', 'ками', 'ках'];
const LATIN_HARD_MASC_SUFFIXES = ['', 'a', 'u', 'e', 'om', 'i', 'ov', 'am', 'ami', 'ah'];
const LATIN_FEM_A_SUFFIXES = ['a', 'i', 'e', 'u', 'oy', 'oyu', 'am', 'ami', 'ah'];
const LATIN_FEM_YA_SUFFIXES = ['ya', 'i', 'e', 'yu', 'ey', 'eyu', 'yam', 'yami', 'yah'];
const LATIN_OK_SUFFIXES = ['ok', 'ka', 'ku', 'ke', 'kom', 'ki', 'kov', 'kam', 'kami', 'kah'];

function buildVariantSet(families: readonly VariantFamily[]): Set<string> {
  const variants = new Set<string>();

  for (const family of families) {
    for (const exact of family.exact ?? []) {
      if (exact) {
        variants.add(exact);
      }
    }

    for (const stem of family.stems) {
      for (const suffix of family.suffixes) {
        const variant = `${stem}${suffix}`;
        if (variant) {
          variants.add(variant);
        }
      }
    }
  }

  return variants;
}

const PROFANITY_VARIANT_FAMILIES: readonly VariantFamily[] = [
  {
    stems: ['сук'],
    suffixes: CYRILLIC_FEM_A_SUFFIXES,
    exact: ['сукин', 'сукина', 'сукину', 'сукины', 'сукиным', 'сукину', 'сукино', 'сукины'],
  },
  {
    stems: ['сцук'],
    suffixes: CYRILLIC_FEM_A_SUFFIXES,
    exact: ['сцука', 'сцуки', 'сцуке', 'сцуку', 'сцукой', 'сцукою', 'сцукам', 'сцуками'],
  },
  {
    stems: ['суч'],
    suffixes: [
      'ка',
      'ки',
      'ке',
      'ку',
      'кой',
      'кою',
      'ек',
      'кам',
      'ками',
      'ках',
      'ара',
      'ары',
      'аре',
      'ару',
      'арой',
      'арою',
      'онок',
      'онка',
      'онку',
      'онки',
    ],
  },
  {
    stems: ['бляд'],
    suffixes: CYRILLIC_SOFT_FEM_SUFFIXES,
    exact: [
      'блядина',
      'блядины',
      'блядине',
      'блядину',
      'блядиной',
      'блядинское',
      'блядинский',
      'блядинская',
      'блядство',
      'блядства',
      'блядству',
      'блядством',
      'блядский',
      'блядская',
      'блядское',
      'блядские',
      'блядского',
      'блядскому',
      'блядскую',
      'блядским',
      'блядских',
      'блядун',
      'блядуна',
      'блядуну',
      'блядуном',
      'блядуны',
    ],
  },
  {
    stems: ['еблан'],
    suffixes: CYRILLIC_HARD_MASC_SUFFIXES,
    exact: [
      'ебланка',
      'ебланки',
      'ебланке',
      'ебланку',
      'ебланкой',
      'ебланский',
      'ебланская',
      'ебланское',
      'ебланские',
      'ебланского',
      'ебланскому',
      'ебланскую',
      'ебланским',
      'ебланских',
    ],
  },
  {
    stems: ['ебнут'],
    suffixes: CYRILLIC_HARD_ADJECTIVE_SUFFIXES,
    exact: [
      'ебнутый',
      'ебнутая',
      'ебнутое',
      'ебнутые',
      'ебнутого',
      'ебнутому',
      'ебнутую',
      'ебнутым',
      'ебнутых',
      'ебанутый',
      'ебанутая',
      'ебанутое',
      'ебанутые',
      'ебанутого',
      'ебанутому',
      'ебанутую',
      'ебанутым',
      'ебанутых',
    ],
  },
  {
    stems: ['ебуч'],
    suffixes: CYRILLIC_ADJECTIVE_SUFFIXES,
    exact: [
      'ебучий',
      'ебучая',
      'ебучее',
      'ебучие',
      'ебучего',
      'ебучему',
      'ебучую',
      'ебучим',
      'ебучих',
    ],
  },
  {
    stems: ['уеб'],
    suffixes: CYRILLIC_OK_SUFFIXES,
    exact: [
      'уебан',
      'уебана',
      'уебану',
      'уебаном',
      'уебаны',
      'уебище',
      'уебища',
      'уебищу',
      'уебищем',
      'уебищный',
      'уебищная',
      'уебищное',
      'уебищные',
    ],
  },
  {
    stems: ['хуйн'],
    suffixes: CYRILLIC_FEM_YA_SUFFIXES,
    exact: [
      'хуевый',
      'хуевая',
      'хуевое',
      'хуевые',
      'хуевого',
      'хуевому',
      'хуевую',
      'хуевым',
      'хуевых',
      'хуило',
      'хуила',
      'хуилу',
      'хуилом',
      'хуйло',
      'хуйла',
      'хуйлу',
      'хуйлом',
      'хуесос',
      'хуесоса',
      'хуесосу',
      'хуесосом',
      'хуесосы',
      'хуета',
      'хуеты',
      'хуету',
      'хуетой',
    ],
  },
  {
    stems: ['хер'],
    suffixes: CYRILLIC_HARD_MASC_SUFFIXES,
    exact: [
      'херовый',
      'херовая',
      'херовое',
      'херовые',
      'херового',
      'херовому',
      'херовую',
      'херовым',
      'херовых',
      'херово',
      'херовина',
      'херовины',
      'херовину',
      'херовиной',
      'херня',
      'херни',
      'херню',
      'херней',
      'хернею',
      'нахер',
      'нахера',
      'нахеру',
      'нахером',
      'охерел',
      'охерела',
      'охерели',
      'охереть',
      'охеренный',
      'охеренная',
      'охеренное',
      'охеренные',
    ],
  },
  {
    stems: ['ебар'],
    suffixes: CYRILLIC_HARD_MASC_SUFFIXES,
    exact: ['ебарь', 'ебаря', 'ебарю', 'ебарем', 'ебари'],
  },
  {
    stems: [],
    suffixes: [],
    exact: ['епт', 'епта', 'ептить', 'йопт', 'йопта', 'пздц'],
  },
  {
    stems: ['пиздюк'],
    suffixes: CYRILLIC_HARD_MASC_SUFFIXES,
    exact: [
      'пиздючка',
      'пиздючки',
      'пиздючке',
      'пиздючку',
      'пиздючкой',
      'пиздюкский',
      'пиздюкская',
      'пиздюкское',
      'пиздюкские',
    ],
  },
  {
    stems: ['пиздобол'],
    suffixes: CYRILLIC_HARD_MASC_SUFFIXES,
    exact: [
      'пиздоболка',
      'пиздоболки',
      'пиздоболке',
      'пиздоболку',
      'пиздобольский',
      'пиздобольская',
      'пиздобольское',
    ],
  },
  {
    stems: ['мраз'],
    suffixes: CYRILLIC_SOFT_FEM_SUFFIXES,
    exact: [
      'мразота',
      'мразоты',
      'мразоте',
      'мразоту',
      'мразотой',
      'мразотою',
      'мразотам',
      'мразотами',
      'мразотах',
      'мразина',
      'мразины',
      'мразину',
      'мразиной',
    ],
  },
  {
    stems: ['шлюх'],
    suffixes: CYRILLIC_FEM_A_SUFFIXES,
    exact: ['шлюшка', 'шлюшки', 'шлюшке', 'шлюшку', 'шлюшкой', 'шлюшками', 'шлюшках'],
  },
  {
    stems: ['шлух'],
    suffixes: CYRILLIC_FEM_A_SUFFIXES,
    exact: ['шлушка', 'шлушки', 'шлушке', 'шлушку', 'шлушкой'],
  },
  {
    stems: ['мудак'],
    suffixes: CYRILLIC_HARD_MASC_SUFFIXES,
    exact: [
      'мудацкий',
      'мудацкая',
      'мудацкое',
      'мудацкие',
      'мудацкого',
      'мудацкому',
      'мудацкую',
      'мудацким',
      'мудацких',
      'мудачье',
      'мудачья',
      'мудачью',
      'мудачьем',
    ],
  },
  {
    stems: ['мудачин'],
    suffixes: CYRILLIC_FEM_A_SUFFIXES,
  },
  {
    stems: ['мудаг'],
    suffixes: CYRILLIC_HARD_MASC_SUFFIXES,
    exact: ['мудажье', 'мудажья', 'мудажью', 'мудажьем'],
  },
  {
    stems: ['мудил'],
    suffixes: CYRILLIC_HARD_MASC_SUFFIXES,
    exact: ['мудила', 'мудилы', 'мудиле', 'мудилу', 'мудилой', 'мудилою', 'мудилам', 'мудилами'],
  },
  {
    stems: ['дибил'],
    suffixes: CYRILLIC_HARD_MASC_SUFFIXES,
    exact: [
      'дибилка',
      'дибилки',
      'дибилке',
      'дибилку',
      'дибилкой',
      'дибильный',
      'дибильная',
      'дибильное',
      'дибильные',
      'дибильного',
      'дибильному',
      'дибильную',
      'дибильным',
      'дибильных',
    ],
  },
  {
    stems: ['долбоеб'],
    suffixes: CYRILLIC_HARD_MASC_SUFFIXES,
    exact: [
      'долбоебка',
      'долбоебки',
      'долбоебке',
      'долбоебку',
      'долбоебкой',
      'долбоебство',
      'долбоебский',
      'долбоебская',
      'долбоебское',
      'долбоебские',
    ],
  },
  {
    stems: ['далбаеб', 'далбоеб', 'долбаеп', 'далбаеп'],
    suffixes: CYRILLIC_HARD_MASC_SUFFIXES,
    exact: [
      'далбаебка',
      'далбаебки',
      'далбаебке',
      'далбаебку',
      'далбаепка',
      'далбаепки',
      'долбаепка',
      'долбаепки',
      'далбоебка',
      'далбоебки',
    ],
  },
  {
    stems: ['ублюд'],
    suffixes: CYRILLIC_OK_SUFFIXES,
    exact: [
      'ублюдочный',
      'ублюдочная',
      'ублюдочное',
      'ублюдочные',
      'ублюдочного',
      'ублюдочному',
      'ублюдочную',
      'ублюдочным',
      'ублюдочных',
    ],
  },
  {
    stems: ['ублют'],
    suffixes: CYRILLIC_OK_SUFFIXES,
    exact: ['ублюток', 'ублютка', 'ублютку', 'ублютке', 'ублютки', 'ублютков'],
  },
  {
    stems: ['твар'],
    suffixes: CYRILLIC_SOFT_FEM_SUFFIXES,
    exact: [
      'тварина',
      'тварины',
      'тварине',
      'тварину',
      'твариной',
      'твариною',
      'тварюга',
      'тварюги',
      'тварюге',
      'тварюгу',
      'тварюгой',
    ],
  },
  {
    stems: ['дебил'],
    suffixes: CYRILLIC_HARD_MASC_SUFFIXES,
    exact: [
      'дебилка',
      'дебилки',
      'дебилке',
      'дебилку',
      'дебилкой',
      'дебильный',
      'дебильная',
      'дебильное',
      'дебильные',
      'дебильного',
      'дебильному',
      'дебильную',
      'дебильным',
      'дебильных',
      'дебилоид',
      'дебилоиды',
      'дебилоида',
      'дебилоиду',
      'дебилизм',
      'дебилизма',
      'дебилизму',
      'дебилизме',
      'дебилизмы',
      'дебилизмом',
    ],
  },
  {
    stems: ['идиот'],
    suffixes: CYRILLIC_HARD_MASC_SUFFIXES,
    exact: [
      'идиотка',
      'идиотки',
      'идиотке',
      'идиотку',
      'идиоткой',
      'идиотизм',
      'идиотизма',
      'идиотизму',
      'идиотизме',
      'идиотизмом',
      'идиотский',
      'идиотская',
      'идиотское',
      'идиотские',
      'идиотского',
      'идиотскому',
      'идиотскую',
      'идиотским',
      'идиотских',
    ],
  },
  {
    stems: ['урод'],
    suffixes: CYRILLIC_HARD_MASC_SUFFIXES,
    exact: [
      'уродка',
      'уродки',
      'уродке',
      'уродку',
      'уродкой',
      'уродина',
      'уродины',
      'уродине',
      'уродину',
      'уродиной',
      'уродский',
      'уродская',
      'уродское',
      'уродские',
      'уродского',
      'уродскому',
      'уродскую',
      'уродским',
      'уродских',
    ],
  },
  {
    stems: ['гандон'],
    suffixes: CYRILLIC_HARD_MASC_SUFFIXES,
    exact: [
      'гандонище',
      'гандонища',
      'гандонищу',
      'гандонищем',
      'гандонский',
      'гандонская',
      'гандонское',
      'гандонские',
      'гандонского',
    ],
  },
  {
    stems: ['пидор'],
    suffixes: CYRILLIC_HARD_MASC_SUFFIXES,
    exact: [
      'пидорский',
      'пидорская',
      'пидорское',
      'пидорские',
      'пидорского',
      'пидорскому',
      'пидорскую',
      'пидорским',
      'пидорских',
      'пидрила',
      'пидрилы',
      'пидриле',
      'пидрилу',
      'пидрилой',
      'пидрильник',
      'пидрильника',
      'пидрильнику',
      'пидорок',
      'пидорка',
      'пидорку',
      'пидорки',
    ],
  },
  {
    stems: ['пидорнут', 'пидарнут'],
    suffixes: CYRILLIC_HARD_ADJECTIVE_SUFFIXES,
  },
  {
    stems: ['пидорас'],
    suffixes: CYRILLIC_HARD_MASC_SUFFIXES,
    exact: [
      'пидарас',
      'пидарасы',
      'пидараса',
      'пидарасу',
      'пидарасом',
      'пидарасами',
      'пидорасина',
      'пидорасины',
      'пидорасине',
      'пидорасину',
      'пидорасиной',
    ],
  },
  {
    stems: ['педор', 'педар'],
    suffixes: CYRILLIC_HARD_MASC_SUFFIXES,
    exact: [
      'педорский',
      'педорская',
      'педорское',
      'педорские',
      'педорского',
      'педорскому',
      'педорскую',
      'педорским',
      'педорских',
      'педарский',
      'педарская',
      'педарское',
      'педарские',
    ],
  },
  {
    stems: ['педик'],
    suffixes: CYRILLIC_HARD_MASC_SUFFIXES,
    exact: [
      'педрила',
      'педрилы',
      'педриле',
      'педрилу',
      'педрилой',
      'педрило',
      'педрилы',
      'педрильник',
      'педрильника',
    ],
  },
  {
    stems: ['гнид'],
    suffixes: CYRILLIC_FEM_A_SUFFIXES,
    exact: ['гнилушка', 'гнилушки', 'гнилушке', 'гнилушку', 'гнилушкой', 'гнидина', 'гнидины'],
  },
  {
    stems: ['сволоч'],
    suffixes: CYRILLIC_SOFT_FEM_SUFFIXES,
    exact: [
      'сволота',
      'сволоты',
      'сволоте',
      'сволоту',
      'сволотой',
      'сволотою',
      'сволочуга',
      'сволочуги',
      'сволочуге',
      'сволочугу',
    ],
  },
  {
    stems: ['паскуд'],
    suffixes: CYRILLIC_FEM_A_SUFFIXES,
    exact: [
      'паскудный',
      'паскудная',
      'паскудное',
      'паскудные',
      'паскудного',
      'паскудному',
      'паскудную',
      'паскудным',
      'паскудных',
      'паскудина',
      'паскудины',
      'паскудину',
    ],
  },
  {
    stems: ['падл'],
    suffixes: CYRILLIC_HARD_FEM_A_SUFFIXES,
    exact: [
      'падло',
      'падлы',
      'падлу',
      'падлой',
      'падлюкой',
      'падлюка',
      'падлюки',
      'падлюке',
      'падлюку',
      'падлюкою',
      'падлюкам',
      'падлюками',
      'падлюках',
    ],
  },
  {
    stems: ['подон'],
    suffixes: CYRILLIC_OK_SUFFIXES,
    exact: [
      'подоночный',
      'подоночная',
      'подоночное',
      'подоночные',
      'подоночного',
      'подоночному',
      'подоночную',
      'подоночным',
      'подоночных',
    ],
  },
  {
    stems: ['мерзав'],
    suffixes: CYRILLIC_EC_SUFFIXES,
    exact: [
      'мерзавка',
      'мерзавки',
      'мерзавке',
      'мерзавку',
      'мерзавкой',
      'мерзавский',
      'мерзавская',
      'мерзавское',
      'мерзавские',
      'мерзавского',
      'мерзавскому',
      'мерзавскую',
    ],
  },
  {
    stems: ['засран'],
    suffixes: CYRILLIC_EC_SUFFIXES,
    exact: [
      'засранка',
      'засранки',
      'засранке',
      'засранку',
      'засранкой',
      'засранцы',
      'засранцев',
      'засранцам',
      'засранцами',
      'засранцах',
    ],
  },
  {
    stems: ['придур'],
    suffixes: CYRILLIC_OK_SUFFIXES,
    exact: [
      'придурочный',
      'придурочная',
      'придурочное',
      'придурочные',
      'придурочного',
      'придурочному',
      'придурочную',
      'придурочным',
      'придурочных',
      'придурь',
      'придури',
      'придурьи',
    ],
  },
  {
    stems: ['кретин'],
    suffixes: CYRILLIC_HARD_MASC_SUFFIXES,
    exact: [
      'кретинка',
      'кретинки',
      'кретинке',
      'кретинку',
      'кретинкой',
      'кретинский',
      'кретинская',
      'кретинское',
      'кретинские',
      'кретинского',
      'кретинскому',
      'кретинскую',
      'кретинским',
      'кретинских',
    ],
  },
  {
    stems: ['стерв'],
    suffixes: CYRILLIC_HARD_FEM_A_SUFFIXES,
    exact: [
      'стервец',
      'стервеца',
      'стервецу',
      'стервецом',
      'стервецы',
      'стервецов',
      'стервецам',
      'стервецами',
      'стервецах',
    ],
  },
  {
    stems: ['имбецил'],
    suffixes: CYRILLIC_HARD_MASC_SUFFIXES,
    exact: [
      'имбецилка',
      'имбецилки',
      'имбецилке',
      'имбецилку',
      'имбецилкой',
      'имбецильный',
      'имбецильная',
      'имбецильное',
      'имбецильные',
      'имбецильного',
      'имбецильному',
      'имбецильную',
      'имбецильным',
      'имбецильных',
    ],
  },
  {
    stems: ['скотин'],
    suffixes: CYRILLIC_FEM_A_SUFFIXES,
    exact: [
      'скотинам',
      'скотинами',
      'скотинах',
      'скотский',
      'скотская',
      'скотское',
      'скотские',
      'скотского',
      'скотскому',
      'скотскую',
      'скотским',
      'скотских',
    ],
  },
  {
    stems: ['залуп'],
    suffixes: CYRILLIC_HARD_FEM_A_SUFFIXES,
    exact: [
      'залупень',
      'залупени',
      'залупенью',
      'залупоглазый',
      'залупоглазая',
      'залупоглазое',
      'залупоглазые',
    ],
  },
  {
    stems: ['манд'],
    suffixes: CYRILLIC_HARD_FEM_A_SUFFIXES,
    exact: [
      'мандавошка',
      'мандавошки',
      'мандавошке',
      'мандавошку',
      'мандавошкой',
      'мандавошками',
      'мандавошках',
    ],
  },
  {
    stems: ['шалав'],
    suffixes: CYRILLIC_HARD_FEM_A_SUFFIXES,
  },
  {
    stems: ['шмар'],
    suffixes: CYRILLIC_HARD_FEM_A_SUFFIXES,
  },
  {
    stems: ['швал'],
    suffixes: CYRILLIC_SOFT_FEM_SUFFIXES,
    exact: ['швалье', 'швалья', 'швалью', 'швальем'],
  },
  {
    stems: ['мудозвон'],
    suffixes: CYRILLIC_HARD_MASC_SUFFIXES,
    exact: [
      'мудозвонка',
      'мудозвонки',
      'мудозвонке',
      'мудозвонку',
      'мудозвонкой',
      'мудозвонский',
      'мудозвонская',
      'мудозвонское',
      'мудозвонские',
    ],
  },
  {
    stems: ['чмошн'],
    suffixes: CYRILLIC_ADJECTIVE_SUFFIXES,
    exact: ['чмо', 'чмырь', 'чмыря', 'чмырю', 'чмырем', 'чмошник', 'чмошника', 'чмошнику'],
  },
  {
    stems: ['говню'],
    suffixes: CYRILLIC_UK_SUFFIXES,
    exact: [
      'говно',
      'гавно',
      'говна',
      'гавна',
      'говну',
      'гавну',
      'говном',
      'гавном',
      'говне',
      'гавне',
      'говнище',
      'говнища',
      'говнищу',
      'говнищем',
      'говенный',
      'говенная',
      'говенное',
      'говенные',
      'говенного',
      'говенному',
      'говенную',
      'говенным',
      'говенных',
      'гавнюк',
      'гавнюка',
      'гавнюку',
      'гавнюком',
      'гавнюки',
    ],
  },
  {
    stems: ['дерьмов'],
    suffixes: CYRILLIC_ADJECTIVE_SUFFIXES,
    exact: [
      'дерьмо',
      'дерьма',
      'дерьму',
      'дерьмом',
      'дерьме',
      'дерьмище',
      'дерьмища',
      'дерьмищу',
      'дерьмищем',
      'дерьмово',
      'дерьмовый',
      'дерьмовая',
      'дерьмовые',
      'дерьмового',
    ],
  },
  {
    stems: ['жоп'],
    suffixes: CYRILLIC_HARD_FEM_A_SUFFIXES,
    exact: [
      'жопе',
      'жопу',
      'жопой',
      'жопою',
      'жопам',
      'жопами',
      'жопах',
      'жопный',
      'жопная',
      'жопное',
      'жопные',
      'жопного',
      'жопному',
      'жопную',
      'жопным',
      'жопных',
    ],
  },
  {
    stems: ['срак'],
    suffixes: CYRILLIC_HARD_FEM_A_SUFFIXES,
    exact: ['срака', 'сраки', 'сраке', 'сраку', 'сракой', 'сракою', 'сракам', 'сраками', 'сраках'],
  },
  {
    stems: ['сран'],
    suffixes: CYRILLIC_EC_SUFFIXES,
    exact: [
      'срань',
      'срани',
      'сранью',
      'сраный',
      'сраная',
      'сраное',
      'сраные',
      'сраного',
      'сраному',
      'сраную',
      'сраным',
      'сраных',
    ],
  },
  {
    stems: ['обосран'],
    suffixes: CYRILLIC_EC_SUFFIXES,
    exact: [
      'обосранный',
      'обосранная',
      'обосранное',
      'обосранные',
      'обосранного',
      'обосранному',
      'обосранную',
      'обосранным',
      'обосранных',
    ],
  },
  {
    stems: ['ссыкл'],
    suffixes: CYRILLIC_HARD_MASC_SUFFIXES,
    exact: [
      'ссыкло',
      'ссыклы',
      'ссыклу',
      'ссыклом',
      'ссыкливый',
      'ссыкливая',
      'ссыкливое',
      'ссыкливые',
      'ссыкливого',
      'ссыкливому',
      'ссыкливую',
    ],
  },
  {
    stems: ['лох'],
    suffixes: CYRILLIC_HARD_MASC_SUFFIXES,
    exact: [
      'лошара',
      'лошары',
      'лошаре',
      'лошару',
      'лошарой',
      'лошарою',
      'лошарам',
      'лошарами',
      'лошарах',
      'лохушка',
      'лохушки',
      'лохушке',
      'лохушку',
      'лохушкой',
    ],
  },
  {
    stems: ['быдл'],
    suffixes: CYRILLIC_HARD_MASC_SUFFIXES,
    exact: [
      'быдло',
      'быдла',
      'быдлу',
      'быдлом',
      'быдляк',
      'быдляка',
      'быдляку',
      'быдляком',
      'быдляки',
      'быдляцкий',
      'быдляцкая',
      'быдляцкое',
      'быдляцкие',
    ],
  },
  {
    stems: ['хамл'],
    suffixes: CYRILLIC_HARD_MASC_SUFFIXES,
    exact: [
      'хамло',
      'хамла',
      'хамлу',
      'хамлом',
      'хамье',
      'хамья',
      'хамью',
      'хамьем',
      'хабалка',
      'хабалки',
      'хабалке',
      'хабалку',
      'хабалкой',
    ],
  },
  {
    stems: ['дрян'],
    suffixes: CYRILLIC_SOFT_FEM_SUFFIXES,
    exact: ['дрянь', 'дряни', 'дрянью', 'дрянной', 'дрянная', 'дрянное', 'дрянные'],
  },
  {
    stems: ['мерзот'],
    suffixes: CYRILLIC_HARD_FEM_A_SUFFIXES,
    exact: ['мерзота', 'мерзоты', 'мерзоте', 'мерзоту', 'мерзотой', 'мерзотою'],
  },
  {
    stems: ['ничтож'],
    suffixes: CYRILLIC_HARD_MASC_SUFFIXES,
    exact: [
      'ничтожество',
      'ничтожества',
      'ничтожеству',
      'ничтожествах',
      'ничтожный',
      'ничтожная',
      'ничтожное',
      'ничтожные',
      'ничтожного',
      'ничтожному',
      'ничтожную',
      'ничтожным',
      'ничтожных',
    ],
  },
  {
    stems: ['тупорыл'],
    suffixes: CYRILLIC_HARD_ADJECTIVE_SUFFIXES,
    exact: ['тупица', 'тупицы', 'тупице', 'тупицу', 'тупицей', 'тупицам', 'тупицами', 'тупицах'],
  },
  {
    stems: ['кончен'],
    suffixes: CYRILLIC_HARD_ADJECTIVE_SUFFIXES,
    exact: [
      'конченный',
      'конченная',
      'конченное',
      'конченные',
      'конченного',
      'конченному',
      'конченную',
      'конченным',
      'конченных',
    ],
  },
  {
    stems: ['дегенерат'],
    suffixes: CYRILLIC_HARD_MASC_SUFFIXES,
    exact: [
      'дегенератка',
      'дегенератки',
      'дегенератке',
      'дегенератку',
      'дегенератский',
      'дегенератская',
      'дегенератское',
    ],
  },
  {
    stems: ['недоум'],
    suffixes: CYRILLIC_OK_SUFFIXES,
    exact: ['недоумок', 'недоумка', 'недоумку', 'недоумком', 'недоумки', 'недоумков'],
  },
  {
    stems: ['отмороз'],
    suffixes: CYRILLIC_OK_SUFFIXES,
    exact: ['отморозок', 'отморозка', 'отморозку', 'отморозком', 'отморозки', 'отморозков'],
  },
  {
    stems: ['pidor'],
    suffixes: LATIN_HARD_MASC_SUFFIXES,
    exact: ['pidoras', 'pidorasy', 'pidorasa', 'pidorasu', 'pidorom', 'pidrila', 'pidrilu'],
  },
  {
    stems: ['mudak'],
    suffixes: LATIN_HARD_MASC_SUFFIXES,
    exact: ['mudachyo', 'mudatskiy', 'mudatskaya', 'mudatskoe', 'mudatskie'],
  },
  {
    stems: ['debil'],
    suffixes: LATIN_HARD_MASC_SUFFIXES,
    exact: ['debilka', 'debilki', 'debilku', 'debilnuy', 'debilnyy', 'debilnaya', 'debilnoe'],
  },
  {
    stems: ['idiot'],
    suffixes: LATIN_HARD_MASC_SUFFIXES,
    exact: ['idiotka', 'idiotki', 'idiotku', 'idiotskiy', 'idiotskaya', 'idiotskoe'],
  },
  {
    stems: ['urod'],
    suffixes: LATIN_HARD_MASC_SUFFIXES,
    exact: ['urodina', 'urodiny', 'urodinu', 'urodskiy', 'urodskaya', 'urodskoe'],
  },
  {
    stems: ['suk'],
    suffixes: LATIN_FEM_A_SUFFIXES,
    exact: ['suchka', 'suchki', 'suchku', 'suchkoy', 'suchara', 'sucharu', 'suchonok'],
  },
  {
    stems: ['blyad'],
    suffixes: ['', 'i', 'yu', 'ey', 'yam', 'yami', 'yah'],
    exact: [
      'blyat',
      'blyadi',
      'blyadyu',
      'blyadina',
      'blyadiny',
      'blyadinu',
      'blyadskij',
      'blyadskiy',
      'blyadskaya',
      'blyadskoe',
      'blyadstvo',
      'blyadstva',
      'blyadstvu',
      'blyadun',
      'blyaduna',
      'blyadunu',
    ],
  },
  {
    stems: ['eblan'],
    suffixes: LATIN_HARD_MASC_SUFFIXES,
    exact: ['eblanka', 'eblanki', 'eblanku', 'eblanskiy', 'eblanskaya', 'eblanskoe'],
  },
  {
    stems: ['ebanut', 'ebnut'],
    suffixes: ['yy', 'iy', 'aya', 'oe', 'ye', 'ogo', 'omu', 'uyu', 'ym', 'yh', 'ymi'],
    exact: ['ebanulyy', 'ebanulaya', 'ebanutoe', 'ebnutyy', 'ebnutaya', 'ebnutoe'],
  },
  {
    stems: ['ueb'],
    suffixes: LATIN_OK_SUFFIXES,
    exact: [
      'ueban',
      'uebana',
      'uebanu',
      'uebanom',
      'uebany',
      'uebishe',
      'uebischa',
      'uebischu',
      'uebischem',
    ],
  },
  {
    stems: ['huyn'],
    suffixes: LATIN_FEM_YA_SUFFIXES,
    exact: [
      'huevyy',
      'huevaya',
      'huevoe',
      'huevye',
      'huilo',
      'huylo',
      'huesos',
      'huesosa',
      'huesosu',
      'huesosom',
      'hueta',
      'huetu',
    ],
  },
  {
    stems: [],
    suffixes: [],
    exact: [
      'naher',
      'nahera',
      'naheru',
      'naherom',
      'hernya',
      'herni',
      'hernyu',
      'oherel',
      'oheret',
    ],
  },
  {
    stems: ['pizdyuk'],
    suffixes: LATIN_HARD_MASC_SUFFIXES,
    exact: ['pizdyuchka', 'pizdyuchki', 'pizdyuchku', 'pizdyukskiy'],
  },
  {
    stems: ['pizdobol'],
    suffixes: LATIN_HARD_MASC_SUFFIXES,
    exact: ['pizdobolka', 'pizdobolki', 'pizdobolku', 'pizdobolskiy'],
  },
  {
    stems: ['scuk'],
    suffixes: LATIN_FEM_A_SUFFIXES,
    exact: ['scuka', 'scuki', 'scuke', 'scuku', 'scukoy', 'scukami'],
  },
  {
    stems: ['mraz'],
    suffixes: ['', 'i', 'yu', 'ey', 'yam', 'yami', 'yah'],
    exact: ['mrazota', 'mrazoty', 'mrazotu', 'mrazina', 'mrazinu'],
  },
  {
    stems: ['shlyuh'],
    suffixes: LATIN_FEM_A_SUFFIXES,
    exact: ['shlyushka', 'shlyushki', 'shlyushku', 'shlyushkoy'],
  },
  {
    stems: ['shluh'],
    suffixes: LATIN_FEM_A_SUFFIXES,
    exact: ['shluka', 'shluki', 'shluku', 'shlukoy'],
  },
  {
    stems: ['gandon'],
    suffixes: LATIN_HARD_MASC_SUFFIXES,
    exact: ['gandonishche', 'gandonam', 'gandonami'],
  },
  {
    stems: ['ublyud'],
    suffixes: LATIN_OK_SUFFIXES,
    exact: ['ublyudochnyy', 'ublyudochnaya', 'ublyudochnoe'],
  },
  {
    stems: ['ublyut'],
    suffixes: LATIN_OK_SUFFIXES,
    exact: ['ublyutok', 'ublyutka', 'ublyutku', 'ublyutke'],
  },
  {
    stems: ['dibil'],
    suffixes: LATIN_HARD_MASC_SUFFIXES,
    exact: ['dibilka', 'dibilki', 'dibilku', 'dibilnyy', 'dibilnaya', 'dibilnoe'],
  },
  {
    stems: ['padl'],
    suffixes: LATIN_FEM_A_SUFFIXES,
    exact: ['padlo', 'padlyuka', 'padlyuki', 'padlyuku', 'padlyukoy'],
  },
  {
    stems: ['zhop'],
    suffixes: LATIN_FEM_A_SUFFIXES,
    exact: ['zhopnyy', 'zhopnaya', 'zhopnoe', 'zhopnye'],
  },
  {
    stems: ['srak'],
    suffixes: LATIN_FEM_A_SUFFIXES,
    exact: ['sraka', 'sraki', 'sraku', 'srakoy'],
  },
  {
    stems: ['sran'],
    suffixes: ['ec', 'ca', 'cu', 'ce', 'cem', 'cy', 'cev', 'cam', 'cami', 'cah'],
    exact: ['sran', 'sranyy', 'sranaya', 'sranoe', 'sranye'],
  },
  {
    stems: ['obosran'],
    suffixes: ['ec', 'ca', 'cu', 'ce', 'cem', 'cy', 'cev', 'cam', 'cami', 'cah'],
    exact: ['obosrannyy', 'obosrannaya', 'obosrannoe', 'obosrannye'],
  },
  {
    stems: ['ssykl'],
    suffixes: LATIN_HARD_MASC_SUFFIXES,
    exact: ['ssyklo', 'ssykly', 'ssyklu', 'ssyklom', 'ssyklivyy', 'ssyklivaya'],
  },
  {
    stems: ['loh', 'lokh'],
    suffixes: LATIN_HARD_MASC_SUFFIXES,
    exact: ['loshara', 'loshary', 'losharu', 'losharoy', 'lohuska', 'lohushka'],
  },
  {
    stems: ['bydl'],
    suffixes: LATIN_HARD_MASC_SUFFIXES,
    exact: ['bydlo', 'bydla', 'bydlu', 'bydlom', 'bydlyak', 'bydlyaki', 'bydlyackiy'],
  },
  {
    stems: ['haml'],
    suffixes: LATIN_HARD_MASC_SUFFIXES,
    exact: ['hamlo', 'hamla', 'hamlu', 'hamlom', 'habalka', 'habalki', 'habalku'],
  },
  {
    stems: ['dryan'],
    suffixes: ['', 'i', 'yu', 'ey', 'yam', 'yami', 'yah'],
    exact: ['dryannoy', 'dryannaya', 'dryannoe', 'dryannye'],
  },
  {
    stems: ['merzot'],
    suffixes: LATIN_FEM_A_SUFFIXES,
    exact: ['merzota', 'merzoty', 'merzotu', 'merzotoy'],
  },
  {
    stems: ['nichtozh'],
    suffixes: LATIN_HARD_MASC_SUFFIXES,
    exact: [
      'nichtozhestvo',
      'nichtozhestva',
      'nichtozhestvu',
      'nichtozhnyy',
      'nichtozhnaya',
      'nichtozhnoe',
    ],
  },
  {
    stems: ['tuporyl'],
    suffixes: ['yy', 'iy', 'aya', 'oe', 'ye', 'ogo', 'omu', 'uyu', 'ym', 'yh', 'ymi'],
    exact: ['tupica', 'tupicy', 'tupicu', 'tupicey'],
  },
  {
    stems: ['konchen'],
    suffixes: ['yy', 'iy', 'aya', 'oe', 'ye', 'ogo', 'omu', 'uyu', 'ym', 'yh', 'ymi'],
    exact: ['konchennyy', 'konchennaya', 'konchennoe', 'konchennye'],
  },
  {
    stems: ['degenerat'],
    suffixes: LATIN_HARD_MASC_SUFFIXES,
    exact: ['degeneratka', 'degeneratki', 'degeneratku', 'degeneratskiy'],
  },
  {
    stems: ['nedoum'],
    suffixes: LATIN_OK_SUFFIXES,
    exact: ['nedoumok', 'nedoumka', 'nedoumku', 'nedoumkom', 'nedoumki'],
  },
  {
    stems: ['otmoroz'],
    suffixes: LATIN_OK_SUFFIXES,
    exact: ['otmorozok', 'otmorozka', 'otmorozku', 'otmorozkom', 'otmorozki'],
  },
  {
    stems: ['zasran'],
    suffixes: ['ec', 'ca', 'cu', 'ce', 'cem', 'cy', 'cev', 'cam', 'cami', 'cah'],
    exact: ['zasranka', 'zasranki', 'zasranku', 'zasrankoy'],
  },
  {
    stems: ['sterv'],
    suffixes: LATIN_FEM_A_SUFFIXES,
    exact: ['stervec', 'sterveca', 'stervecu', 'stervecom', 'stervecy'],
  },
  {
    stems: ['zalup'],
    suffixes: LATIN_FEM_A_SUFFIXES,
    exact: ['zalupen', 'zalupenyu', 'zalupoglazyy', 'zalupoglazaya', 'zalupoglazoe'],
  },
  {
    stems: ['mand'],
    suffixes: LATIN_FEM_A_SUFFIXES,
    exact: ['mandavoshka', 'mandavoshki', 'mandavoshku', 'mandavoshkoy'],
  },
  {
    stems: ['shalav'],
    suffixes: LATIN_FEM_A_SUFFIXES,
  },
  {
    stems: ['shmar'],
    suffixes: LATIN_FEM_A_SUFFIXES,
  },
  {
    stems: ['shval'],
    suffixes: ['', 'i', 'yu', 'ey', 'yam', 'yami', 'yah'],
    exact: ['shvalyo', 'shvalya', 'shvalyu', 'shvalyem'],
  },
  {
    stems: ['mudozvon'],
    suffixes: LATIN_HARD_MASC_SUFFIXES,
    exact: ['mudozvonka', 'mudozvonki', 'mudozvonku', 'mudozvonskiy', 'mudozvonskaya'],
  },
  {
    stems: ['mudag'],
    suffixes: LATIN_HARD_MASC_SUFFIXES,
    exact: ['mudazhyo', 'mudazhya', 'mudazhyu', 'mudazhyem'],
  },
  {
    stems: ['dalbaeb', 'dalboeb', 'dolbaep', 'dalbaep'],
    suffixes: LATIN_HARD_MASC_SUFFIXES,
    exact: ['dalbaebka', 'dalboebka', 'dolbaepka', 'dalbaepka'],
  },
  {
    stems: ['pedor', 'pedar'],
    suffixes: LATIN_HARD_MASC_SUFFIXES,
    exact: ['pedorskiy', 'pedorskaya', 'pedarskiy', 'pedarskaya'],
  },
];

const TARGETED_INSULT_VARIANT_FAMILIES: readonly VariantFamily[] = [
  {
    stems: ['дурак'],
    suffixes: CYRILLIC_HARD_MASC_SUFFIXES,
    exact: [
      'дура',
      'дуры',
      'дуре',
      'дуру',
      'дурой',
      'дурою',
      'дурам',
      'дурами',
      'дурах',
      'дурочка',
      'дурочки',
      'дурочке',
      'дурочку',
      'дурочкой',
      'дурында',
      'дурынды',
      'дурынде',
      'дурынду',
      'дурындой',
    ],
  },
  {
    stems: ['даун'],
    suffixes: CYRILLIC_HARD_MASC_SUFFIXES,
    exact: [
      'дауны',
      'даунов',
      'даунам',
      'даунами',
      'даунах',
      'даунский',
      'даунская',
      'даунское',
      'даунские',
    ],
  },
  {
    stems: ['аутист'],
    suffixes: CYRILLIC_HARD_MASC_SUFFIXES,
    exact: [
      'аутисты',
      'аутистов',
      'аутистам',
      'аутистами',
      'аутистах',
      'аутистка',
      'аутистки',
      'аутистке',
      'аутистку',
      'аутисткой',
    ],
  },
  {
    stems: ['псих'],
    suffixes: CYRILLIC_HARD_MASC_SUFFIXES,
    exact: [
      'психи',
      'психов',
      'психам',
      'психами',
      'психах',
      'психопат',
      'психопата',
      'психопату',
      'психопатом',
      'психопаты',
      'психопатка',
      'психопатки',
      'психопатку',
    ],
  },
  {
    stems: ['шизик'],
    suffixes: CYRILLIC_HARD_MASC_SUFFIXES,
    exact: [
      'шиза',
      'шизы',
      'шизе',
      'шизу',
      'шизой',
      'шизоид',
      'шизоида',
      'шизоиду',
      'шизоидом',
      'шизоиды',
      'шизоидка',
      'шизоидки',
      'шизоидку',
    ],
  },
  {
    stems: ['нарик'],
    suffixes: CYRILLIC_HARD_MASC_SUFFIXES,
    exact: [
      'наркоман',
      'наркомана',
      'наркоману',
      'наркоманом',
      'наркоманы',
      'наркоманка',
      'наркоманки',
      'наркоманку',
    ],
  },
  {
    stems: ['алкаш'],
    suffixes: CYRILLIC_HARD_MASC_SUFFIXES,
    exact: [
      'алкоголик',
      'алкоголика',
      'алкоголику',
      'алкоголиком',
      'алкоголики',
      'алкоголичка',
      'алкоголички',
      'алкоголичку',
    ],
  },
  {
    stems: ['додик'],
    suffixes: CYRILLIC_HARD_MASC_SUFFIXES,
  },
  {
    stems: [],
    suffixes: [],
    exact: [
      'тупой',
      'тупая',
      'тупое',
      'тупые',
      'тупого',
      'тупому',
      'тупую',
      'тупым',
      'тупых',
      'глупый',
      'глупая',
      'глупое',
      'глупые',
      'глупого',
      'глупому',
      'глупую',
      'глупым',
      'глупых',
    ],
  },
  {
    stems: ['жирдяй'],
    suffixes: CYRILLIC_HARD_MASC_SUFFIXES,
    exact: [
      'жирный',
      'жирная',
      'жирное',
      'жирные',
      'жирного',
      'жирному',
      'жирную',
      'жирным',
      'жирных',
      'жируха',
      'жирухи',
      'жируху',
      'жирухой',
      'жиртрест',
      'жиртреста',
      'жиртресту',
      'жиртрестом',
    ],
  },
  {
    stems: ['вонюч'],
    suffixes: CYRILLIC_ADJECTIVE_SUFFIXES,
    exact: [
      'вонючка',
      'вонючки',
      'вонючке',
      'вонючку',
      'вонючкой',
      'вонючий',
      'вонючая',
      'вонючее',
      'вонючие',
      'вонючего',
    ],
  },
  {
    stems: ['петух'],
    suffixes: CYRILLIC_HARD_MASC_SUFFIXES,
    exact: ['петухи'],
  },
  {
    stems: ['баран'],
    suffixes: CYRILLIC_HARD_MASC_SUFFIXES,
    exact: ['бараны'],
  },
  {
    stems: ['крыс'],
    suffixes: CYRILLIC_HARD_FEM_A_SUFFIXES,
  },
  {
    stems: ['макак'],
    suffixes: CYRILLIC_FEM_A_SUFFIXES,
  },
  {
    stems: ['чурк'],
    suffixes: CYRILLIC_HARD_FEM_A_SUFFIXES,
  },
  {
    stems: ['шкур'],
    suffixes: CYRILLIC_HARD_FEM_A_SUFFIXES,
  },
  {
    stems: ['durak'],
    suffixes: LATIN_HARD_MASC_SUFFIXES,
    exact: ['dura', 'dury', 'durakami', 'durochka', 'durochku'],
  },
  {
    stems: ['daun', 'autist', 'psih', 'psyh', 'nark', 'alkash', 'dodik'],
    suffixes: LATIN_HARD_MASC_SUFFIXES,
  },
  {
    stems: ['petuh', 'baran', 'krys', 'makak', 'churk', 'shkur'],
    suffixes: LATIN_HARD_MASC_SUFFIXES,
    exact: ['kozel', 'kozla', 'kozlu', 'kozlom', 'osel', 'osla', 'oslu', 'oslom'],
  },
  {
    stems: [],
    suffixes: [],
    exact: [
      'козел',
      'козла',
      'козлу',
      'козлом',
      'козлы',
      'козлов',
      'козлам',
      'козлами',
      'осел',
      'осла',
      'ослу',
      'ослом',
      'ослы',
      'ослов',
      'ослам',
      'ослами',
      'овца',
      'овцы',
      'овце',
      'овцу',
      'овцой',
      'овцою',
      'овцами',
      'свинья',
      'свиньи',
      'свинье',
      'свинью',
      'свиньей',
      'свиньею',
      'свиней',
      'свиньями',
      'обезьяна',
      'обезьяны',
      'обезьяне',
      'обезьяну',
      'обезьяной',
      'обезьяною',
      'обезьянами',
      'днище',
      'днища',
      'днищу',
      'днищем',
      'svinya',
      'svinyi',
      'svinyu',
      'ovca',
      'ovcu',
      'obezyana',
      'obezyanu',
      'dnische',
      'dnishche',
      'zhirdyay',
      'zhirnyy',
      'zhirnaya',
      'vonyuchka',
    ],
  },
];

const EXACT_PROFANITY_VARIANTS = buildVariantSet(PROFANITY_VARIANT_FAMILIES);
const TARGETED_INSULT_VARIANTS = buildVariantSet(TARGETED_INSULT_VARIANT_FAMILIES);

export const PROFANITY_EXACT_VARIANT_COUNT = EXACT_PROFANITY_VARIANTS.size;
export const TARGETED_INSULT_VARIANT_COUNT = TARGETED_INSULT_VARIANTS.size;

export function isExactProfanityVariant(value: string): boolean {
  return EXACT_PROFANITY_VARIANTS.has(value);
}

export function isTargetedInsultVariant(value: string): boolean {
  return TARGETED_INSULT_VARIANTS.has(value);
}
