// Generated by scripts/generate-commercial-ocr-detector-source.mjs. Do not edit by hand.
export const COMMERCIAL_OCR_DETECTOR_SOURCE_SHA256 = 'aa2eed465a790bbe301e354c86e8525ada4bc9dda6f351f9153398008bb1797a' as const;
export const COMMERCIAL_OCR_DETECTOR_SOURCE_FILE_COUNT = 44 as const;
export const COMMERCIAL_OCR_RUNTIME_SOURCE_SHA256 = '102fd63b863a486c560f6bc7d6bfaac07200a8b27a992101f4444bd48fe5de28' as const;
export const COMMERCIAL_OCR_RUNTIME_SOURCE_FILE_COUNT = 69 as const;
export const COMMERCIAL_OCR_POLICY_SOURCE_SHA256 = 'c94c9a2cc11c3d87833279c936e05d632467f8c1f39f4f96bd016c4b8f4c3608' as const;
export const COMMERCIAL_OCR_POLICY_SOURCE_FILE_COUNT = 4 as const;
export const COMMERCIAL_OCR_PREPROCESS_SOURCE_SHA256 = '2b9d3c4cb0b8ef04dbe735cdffe2f72883fb834c20d2b0ad754f85930cde7227' as const;
export const COMMERCIAL_OCR_PREPROCESS_SOURCE_FILE_COUNT = 4 as const;
export const COMMERCIAL_OCR_AUDIT_TOOL_SOURCE_SHA256 = '47fa3e5fe9ab2aa00aa4af61d21870f979ad3cf4fe5bbaed85d8dcf95e31e823' as const;
export const COMMERCIAL_OCR_AUDIT_TOOL_SOURCE_FILE_COUNT = 41 as const;
export const COMMERCIAL_OCR_BUILD_IDENTITY = {
  "nodeBaseImage": {
    "reference": "node:24-alpine",
    "digest": "sha256:d32cdf619f63fe0471182d08996dd516c6275bb5fd31ae06e55a570bd9e1ad43"
  },
  "packages": {
    "sharp": {
      "name": "sharp",
      "version": "0.35.4",
      "integrity": "sha512-n++8XWcj+jCOr2IOl7h8LbKnGBDY4aPbmprMONBNFdn0ImXqpGVv5zliDs0V9HbmbCQLpbuo2ej9rAoOQTvMDA=="
    },
    "tesseract": {
      "name": "tesseract-ocr",
      "version": "5.5.2-r0"
    },
    "traineddataEng": {
      "name": "tesseract-ocr-data-eng",
      "version": "5.5.2-r0"
    },
    "traineddataRus": {
      "name": "tesseract-ocr-data-rus",
      "version": "5.5.2-r0"
    }
  }
} as const;
export const COMMERCIAL_OCR_PRODUCTION_NATIVE_ENVIRONMENT = {
  "COMMERCIAL_OCR_TESSERACT_CONCURRENCY": 1,
  "COMMERCIAL_OCR_TESSERACT_MAX_QUEUE": 4,
  "COMMERCIAL_OCR_TESSERACT_TIMEOUT_MS": 10000,
  "OMP_THREAD_LIMIT": 1
} as const;
