// Generated by scripts/generate-commercial-ocr-detector-source.mjs. Do not edit by hand.
export const COMMERCIAL_OCR_DETECTOR_SOURCE_SHA256 = 'c7e8badb68fc7d899797e01d1ae9bfd0f896cb760271a911318ec8d29cd96e5e' as const;
export const COMMERCIAL_OCR_DETECTOR_SOURCE_FILE_COUNT = 44 as const;
export const COMMERCIAL_OCR_RUNTIME_SOURCE_SHA256 = 'bc0ded33c083afdfc1c6fd589d326ed1a801533f51d1fcd61c2d07335faf9e70' as const;
export const COMMERCIAL_OCR_RUNTIME_SOURCE_FILE_COUNT = 69 as const;
export const COMMERCIAL_OCR_POLICY_SOURCE_SHA256 = 'c94c9a2cc11c3d87833279c936e05d632467f8c1f39f4f96bd016c4b8f4c3608' as const;
export const COMMERCIAL_OCR_POLICY_SOURCE_FILE_COUNT = 4 as const;
export const COMMERCIAL_OCR_PREPROCESS_SOURCE_SHA256 = '2b9d3c4cb0b8ef04dbe735cdffe2f72883fb834c20d2b0ad754f85930cde7227' as const;
export const COMMERCIAL_OCR_PREPROCESS_SOURCE_FILE_COUNT = 4 as const;
export const COMMERCIAL_OCR_AUDIT_TOOL_SOURCE_SHA256 = '14a66927a419e5f80da241816574a6bc3c9c6a84c6599e8a179ad300f37c88fe' as const;
export const COMMERCIAL_OCR_AUDIT_TOOL_SOURCE_FILE_COUNT = 41 as const;
export const COMMERCIAL_OCR_BUILD_IDENTITY = {
  "nodeBaseImage": {
    "reference": "node:24-alpine",
    "digest": "sha256:d32cdf619f63fe0471182d08996dd516c6275bb5fd31ae06e55a570bd9e1ad43"
  },
  "packages": {
    "sharp": {
      "name": "sharp",
      "version": "0.35.4",
      "integrity": "sha512-n++8XWcj+jCOr2IOl7h8LbKnGBDY4aPbmprMONBNFdn0ImXqpGVv5zliDs0V9HbmbCQLpbuo2ej9rAoOQTvMDA=="
    },
    "tesseract": {
      "name": "tesseract-ocr",
      "version": "5.5.2-r0"
    },
    "traineddataEng": {
      "name": "tesseract-ocr-data-eng",
      "version": "5.5.2-r0"
    },
    "traineddataRus": {
      "name": "tesseract-ocr-data-rus",
      "version": "5.5.2-r0"
    }
  }
} as const;
export const COMMERCIAL_OCR_PRODUCTION_NATIVE_ENVIRONMENT = {
  "COMMERCIAL_OCR_TESSERACT_CONCURRENCY": 1,
  "COMMERCIAL_OCR_TESSERACT_MAX_QUEUE": 4,
  "COMMERCIAL_OCR_TESSERACT_TIMEOUT_MS": 10000,
  "OMP_THREAD_LIMIT": 1
} as const;
