// Generated by scripts/generate-commercial-ocr-detector-source.mjs. Do not edit by hand.
export const COMMERCIAL_OCR_DETECTOR_SOURCE_SHA256 = 'c97c18ede90591310b629d43c2a00a9266294e1cc88fba46a855127a42fde4e7' as const;
export const COMMERCIAL_OCR_DETECTOR_SOURCE_FILE_COUNT = 27 as const;
export const COMMERCIAL_OCR_RUNTIME_SOURCE_SHA256 = 'efda9800239b2ef4da3e0103cfc3951b58345280613e92bce9233313e0a4d885' as const;
export const COMMERCIAL_OCR_RUNTIME_SOURCE_FILE_COUNT = 34 as const;
export const COMMERCIAL_OCR_POLICY_SOURCE_SHA256 = 'a6c4dc8b740d0e4d9e5e749be1329a6a126c257fe6338cc496b896a752f7dd8b' as const;
export const COMMERCIAL_OCR_POLICY_SOURCE_FILE_COUNT = 4 as const;
export const COMMERCIAL_OCR_PREPROCESS_SOURCE_SHA256 = 'bcb033a076ca101763e647a9360d259e69cc4442089d21eb541d0cf22d17ba6d' as const;
export const COMMERCIAL_OCR_PREPROCESS_SOURCE_FILE_COUNT = 2 as const;
export const COMMERCIAL_OCR_AUDIT_TOOL_SOURCE_SHA256 = 'a5dd8dd9c3b47ee0cdb4136a441badfdc1b70fead420b0c0b455c7c89ba273d3' as const;
export const COMMERCIAL_OCR_AUDIT_TOOL_SOURCE_FILE_COUNT = 32 as const;
export const COMMERCIAL_OCR_BUILD_IDENTITY = {
  "nodeBaseImage": {
    "reference": "node:24-alpine",
    "digest": "sha256:d32cdf619f63fe0471182d08996dd516c6275bb5fd31ae06e55a570bd9e1ad43"
  },
  "packages": {
    "sharp": {
      "name": "sharp",
      "version": "0.35.3",
      "integrity": "sha512-ej0zVHuZGHCiABXcNxeYhpRnPNPAcvbG8RMdBAhDAxLKkCRVSpK3Iyu7qbqw3JMzoj0REeM6f3tJLtVwl0023Q=="
    },
    "tesseract": {
      "name": "tesseract-ocr",
      "version": "5.5.2-r0"
    },
    "traineddataEng": {
      "name": "tesseract-ocr-data-eng",
      "version": "5.5.2-r0"
    },
    "traineddataRus": {
      "name": "tesseract-ocr-data-rus",
      "version": "5.5.2-r0"
    }
  }
} as const;
export const COMMERCIAL_OCR_PRODUCTION_NATIVE_ENVIRONMENT = {
  "COMMERCIAL_OCR_TESSERACT_CONCURRENCY": 1,
  "COMMERCIAL_OCR_TESSERACT_MAX_QUEUE": 4,
  "COMMERCIAL_OCR_TESSERACT_TIMEOUT_MS": 10000,
  "OMP_THREAD_LIMIT": 1
} as const;
