import type { CommercialLabeledPattern } from './commercial-patterns';

export const SERVICE_SPECIALTY_REQUIRED_VOCABULARY: Readonly<Record<string, readonly string[]>> = {
  'banquet-hall-catalog': ['банкетн'],
  'well-drilling-self-offer': ['скважин'],
  'cosmetic-procedure-catalog': ['коррекци', 'мезотерапи', 'липолитик', 'пирсинг'],
  'construction-service-catalog': ['строительн', 'полусух'],
  'divination-self-offer': ['потомственн', 'эксперт', 'гадаю', 'предсказываю', 'ясновидящ'],
  'seasonal-lodging-offer': ['местн', 'номер', 'комнат'],
  'tile-finishing-works': [
    'плитк',
    'плиточн',
    'отделочн',
    'поклейк',
    'оклейк',
    'шпаклевк',
    'покраск',
    'электромонтаж',
  ],
  'electrical-wiring-service': ['проводк', 'сборк', 'устройств', 'заземлен'],
  'pest-control-service': ['дезинсекц', 'дезинфекц', 'дератизац', 'уничтожени', 'обработк'],
  'cosmetic-removal-service': ['удаляем', 'удалени', 'дерматоскопи'],
  'garden-treatment-service': ['проведу', 'проводим', 'обработк'],
  'delivery-platform-onboarding': ['яндекс', 'самокат', 'delivery', 'доставк'],
  'digital-service': [
    'разработк',
    'создани',
    'сделаю',
    'настрою',
    'чиню',
    'меняю',
    'восстановлени',
  ],
  'pet-grooming-service': ['груминг', 'стрижк', 'выч', 'купани'],
  'beauty-salon-service': ['салон', 'красот', 'мастер', 'парикмах'],
  'print-copy-service': ['печать', 'распечатк', 'ксерокопи', 'копировальн', 'ламинировани'],
  'tool-rental-service': [
    'перфоратор',
    'болгарк',
    'сварочн',
    'виброплит',
    'бетономешалк',
    'строительн',
    'инструмент',
  ],
  'locksmith-service': ['вскрыти', 'замен', 'аварийн', 'мастер', 'изготовлени'],
  'well-drilling-service': ['скважин', 'обсадн'],
  'sewer-cleaning-service': ['канализаци', 'устранени', 'сантехник'],
  'kids-event-service': ['аниматор', 'аквагрим', 'мыльн', 'праздник'],
  'legal-document-service': ['юридическ', 'составлю', 'подготовк', 'представительств'],
  'balcony-glazing-service': ['остекл', 'утепл', 'отделк'],
  'construction-contractor': ['подряд'],
  'sauna-under-key-service': ['ключ', 'сборк', 'решени'],
  'crane-beam-installation': ['производств', 'изготовлени', 'монтаж'],
  'custom-handmade-order': [
    'заказ',
    'табличк',
    'тапочк',
    'кошел',
    'портмоне',
    'ремн',
    'сумк',
    'клатч',
    'органайзер',
    'гравировк',
    'текст',
    'работ',
    'песн',
    'трек',
  ],
  'custom-3d-printing': ['принтер', 'печать'],
  'inflatable-trampoline-rental': ['надувн'],
  'custom-gingerbread-order': ['имбирн', 'принима'],
  'custom-ribbon-bouquet': ['атласн'],
  'address-sign-service': ['изготовлени', 'изготавлива', 'изготовлю', 'изготовим'],
  'custom-forged-flower': ['кован'],
  'custom-song-package': ['рождени', 'свадьб', 'годовщин', 'выпускн', 'признани'],
  'memorial-video-service': ['ролик', 'видео'],
  'local-mowing-self-offer': ['скашу'],
  'wedding-decoration-rental': ['украшени'],
  'organized-tour-service': ['авторск', 'тур', 'туры', 'маршрут', 'поездк', 'стоимост'],
  'website-creation-service': ['созда'],
  'clothing-repair-service': ['ремонт'],
  'custom-art-order': ['портрет', 'дерев', 'картина', 'печать'],
  'promotion-service': [
    'smm',
    'таргет',
    'директолог',
    'яндекс',
    'контекстн',
    'настро',
    'продвижени',
  ],
  'vehicle-ad-placement': ['размест', 'размещени'],
  'marketing-automation': ['рассылк', 'софт', 'бот', 'инструмент', 'клиент', 'заявк'],
  'logistics-delivery': ['переезд', 'перевозк', 'доставк', 'сборн', 'грузоперевоз'],
  'taxi-transport-service': ['такси', 'трансфер', 'межгород', 'пассажирск', 'поездк'],
  'taxi-driver-self-offer': ['таксист'],
  'taxiing-contact-self-offer': ['такс'],
  'advance-airport-station-transfer': ['предварительн'],
  'professional-passenger-parcel-transfer': ['пассажир'],
  'scheduled-round-trip-parcel-route': ['посыл'],
  'scheduled-round-trip-door-to-door': ['водител'],
  'event-bus-hire': ['автобус'],
  'scheduled-passenger-parcel-route': ['свободн'],
  'multi-route-transport-table': ['довез', 'отвез', 'доставим', 'пассажирск'],
  'taxi-callsign-availability': ['такси'],
  'appliance-repair': ['холодильник', 'стиральн', 'кондиционер', 'систем', 'техник'],
  'stretch-ceiling-service': ['натяжн', 'потолк'],
  'septic-excavator-service': ['выгребн', 'септик', 'экскаватор', 'самосвал'],
  'custom-song-service': ['песн', 'трек', 'музык', 'поздравлен'],
  'debt-relief-service': ['списани', 'банкротств', 'рефинансировани'],
  'accounting-service': ['бухгалтер', 'тност', 'деклараци', 'налог', 'кадров'],
  'currency-exchange-service': ['обменник', 'пункт', 'обмен'],
  'medical-service': [
    'стоматолог',
    'медицинск',
    'клиник',
    'узи',
    'анализ',
    'имплантаци',
    'врач',
    'терапевт',
    'невролог',
  ],
  'rehab-center-service': ['реабилитационн', 'реабилитаци', 'программ', 'терапи'],
  'addiction-detox-service': ['вывод', 'кодировк', 'сняти', 'отравлени', 'похмель', 'зависимост'],
  'internet-connection-service': [
    'беспроводн',
    'домашн',
    'частн',
    'ростелеком',
    'wink',
    'видеонаблюдени',
    'мобильн',
    'интернет',
    'подключени',
  ],
  'speech-therapy-lessons': ['логопед', 'запуск', 'звукопроизношени', 'заговорит'],
  'cleaning-service': ['клининг', 'уборк', 'мойк', 'генеральн', 'спецуборк'],
  'moving-cargo-service': ['грузоперевоз', 'переезд', 'перевозк'],
  'tree-yard-repair-service': ['спил', 'обрезк', 'обреж', 'сварочн', 'изготовлени'],
  'yard-cleanup-service': ['спил', 'покос', 'построек', 'вывоз', 'копк'],
  'paving-landscaping-service': [
    'асфальтировани',
    'брусчатк',
    'установк',
    'бетонировани',
    'благоустройств',
  ],
  'language-tutor': ['английск', 'китайск', 'немецк', 'французск', 'испанск'],
  'tattoo-service': ['тату', 'татуаж', 'тату-мастер'],
  'document-service': ['водительск', 'категор', 'документ'],
  'concrete-works': ['бетонн', 'бетонировани'],
  'mosquito-net-service': ['москитн'],
  'insurance-service': ['страховани', 'осаго', 'каско', 'кбм'],
  'tour-agency': ['турагентств', 'туры', 'туров', 'отел'],
  'tourist-lodging-offer': ['домик', 'номер', 'гостев'],
  'cadastral-service': ['кадастров', 'межеван', 'границ', 'техническ', 'оформлени'],
  'подъем-домов': ['под'],
  'замена-венцов': ['замен'],
  'ремонт-фундаментов': ['фундамент'],
  'строительство-пристроек': ['строительств'],
  'пластиковые-окна': ['пластиков', 'замен', 'монтаж', 'установк'],
  'pvc-window-door-repair': ['ремонт', 'обслуживани'],
  'каменный-ковер': ['каменн', 'бесшовн', 'покрыти'],
  техприсоединение: ['технологическ', 'электрическ', 'компани', 'антимонопольн', 'досудебн'],
};

export function selectServiceSpecialtyPatterns(
  patterns: readonly CommercialLabeledPattern[],
  rawLoweredText: string,
  normalizedText: string,
): CommercialLabeledPattern[] {
  return patterns.filter(({ label }) => {
    const requiredVocabulary = SERVICE_SPECIALTY_REQUIRED_VOCABULARY[label];
    if (!requiredVocabulary) {
      return true;
    }

    return requiredVocabulary.some(
      (token) =>
        rawLoweredText.includes(token) ||
        (normalizedText !== rawLoweredText && normalizedText.includes(token)),
    );
  });
}
