export const VK_PARSING_MAX_PHOTOS = 10,
  VK_PARSING_MAX_VIDEOS = 1,
  VK_PARSING_MAX_LINKS = 20;
export const VK_PARSING_MAX_PUBLISH_TEXT_LENGTH = 4_000;
export const VK_PARSING_MAX_CHANNEL_LINK_TEXT_LENGTH = 120;
export const VK_PARSING_MAX_CHANNEL_LINK_URL_LENGTH = 256;
export const VK_PARSING_DEFAULT_CHANNEL_LINK_TEXT = 'Подписаться на канал';
