#!/usr/bin/env bash
# Generated by scripts/agent/generate-deploy-impact-bash.mjs. Do not edit by hand.
# Source: config/change-impact.json sha256=112d8a525ab3ac61a0c8dd60ac0e094f911899108cb79c2e7139fe2f798a6a3c

readonly MAXIM_IMPACT_RULE_0_INCLUDE_REGEX='^((AGENTS\.md)|((.*/)?AGENTS\.md)|((.*/)?[^/]*\.md)|(README\.md)|(docs/.*)|(\.env\.example)|(infra/env/.*))$'
readonly MAXIM_IMPACT_RULE_1_INCLUDE_REGEX='^((config/change-impact\.json)|(scripts/agent/.*))$'
readonly MAXIM_IMPACT_RULE_2_INCLUDE_REGEX='^((config/prisma-migration-policy\.json))$'
readonly MAXIM_IMPACT_RULE_3_INCLUDE_REGEX='^((\.editorconfig)|(\.gitattributes)|(\.gitignore)|(\.prettierrc\.json)|(eslint\.config\.mjs)|(\.github/.*)|(\.husky/.*)|(scripts/.*))$'
readonly MAXIM_IMPACT_RULE_3_EXCLUDE_REGEX='^((scripts/agent/.*))$'
readonly MAXIM_IMPACT_RULE_4_INCLUDE_REGEX='^((package-lock\.json))$'
readonly MAXIM_IMPACT_RULE_5_INCLUDE_REGEX='^((package\.json)|(tsconfig\.base\.json)|(\.npmrc)|(\.dockerignore))$'
readonly MAXIM_IMPACT_RULE_6_INCLUDE_REGEX='^((\.nvmrc))$'
readonly MAXIM_IMPACT_RULE_7_INCLUDE_REGEX='^((bot\.webp)|(frendly\.webp)|(joker\.webp)|(police\.webp))$'
readonly MAXIM_IMPACT_RULE_8_INCLUDE_REGEX='^((packages/contracts/(.*/)?[^/]*\.spec\.ts)|(packages/contracts/(.*/)?[^/]*\.test\.ts)|(packages/contracts/test/.*)|(packages/contracts/(.*/)?__tests__/.*))$'
readonly MAXIM_IMPACT_RULE_9_INCLUDE_REGEX='^((packages/contracts/.*))$'
readonly MAXIM_IMPACT_RULE_9_EXCLUDE_REGEX='^(((.*/)?AGENTS\.md)|((.*/)?[^/]*\.md)|(packages/contracts/(.*/)?[^/]*\.spec\.ts)|(packages/contracts/(.*/)?[^/]*\.test\.ts)|(packages/contracts/test/.*)|(packages/contracts/(.*/)?__tests__/.*))$'
readonly MAXIM_IMPACT_RULE_10_INCLUDE_REGEX='^((apps/api/(.*/)?[^/]*\.spec\.ts)|(apps/api/(.*/)?[^/]*\.test\.ts)|(apps/api/test/.*)|(apps/api/(.*/)?__tests__/.*))$'
readonly MAXIM_IMPACT_RULE_11_INCLUDE_REGEX='^((apps/api/prisma/schema\.prisma))$'
readonly MAXIM_IMPACT_RULE_12_INCLUDE_REGEX='^((apps/api/prisma/migrations/.*))$'
readonly MAXIM_IMPACT_RULE_13_INCLUDE_REGEX='^((apps/api/prisma\.config\.ts)|(apps/api/prisma/seed\.ts))$'
readonly MAXIM_IMPACT_RULE_14_INCLUDE_REGEX='^((apps/api/.*))$'
readonly MAXIM_IMPACT_RULE_14_EXCLUDE_REGEX='^(((.*/)?AGENTS\.md)|((.*/)?[^/]*\.md)|(apps/api/(.*/)?[^/]*\.spec\.ts)|(apps/api/(.*/)?[^/]*\.test\.ts)|(apps/api/test/.*)|(apps/api/(.*/)?__tests__/.*))$'
readonly MAXIM_IMPACT_RULE_15_INCLUDE_REGEX='^((apps/miniapp/(.*/)?[^/]*\.spec\.ts)|(apps/miniapp/(.*/)?[^/]*\.spec\.tsx)|(apps/miniapp/(.*/)?[^/]*\.test\.ts)|(apps/miniapp/(.*/)?[^/]*\.test\.tsx)|(apps/miniapp/test/.*)|(apps/miniapp/(.*/)?__tests__/.*))$'
readonly MAXIM_IMPACT_RULE_16_INCLUDE_REGEX='^((apps/miniapp/.*))$'
readonly MAXIM_IMPACT_RULE_16_EXCLUDE_REGEX='^(((.*/)?AGENTS\.md)|((.*/)?[^/]*\.md)|(apps/miniapp/(.*/)?[^/]*\.spec\.ts)|(apps/miniapp/(.*/)?[^/]*\.spec\.tsx)|(apps/miniapp/(.*/)?[^/]*\.test\.ts)|(apps/miniapp/(.*/)?[^/]*\.test\.tsx)|(apps/miniapp/test/.*)|(apps/miniapp/(.*/)?__tests__/.*))$'
readonly MAXIM_IMPACT_RULE_17_INCLUDE_REGEX='^((apps/admin/(.*/)?[^/]*\.spec\.ts)|(apps/admin/(.*/)?[^/]*\.spec\.tsx)|(apps/admin/(.*/)?[^/]*\.test\.ts)|(apps/admin/(.*/)?[^/]*\.test\.tsx)|(apps/admin/test/.*)|(apps/admin/(.*/)?__tests__/.*))$'
readonly MAXIM_IMPACT_RULE_18_INCLUDE_REGEX='^((apps/admin/.*))$'
readonly MAXIM_IMPACT_RULE_18_EXCLUDE_REGEX='^(((.*/)?AGENTS\.md)|((.*/)?[^/]*\.md)|(apps/admin/(.*/)?[^/]*\.spec\.ts)|(apps/admin/(.*/)?[^/]*\.spec\.tsx)|(apps/admin/(.*/)?[^/]*\.test\.ts)|(apps/admin/(.*/)?[^/]*\.test\.tsx)|(apps/admin/test/.*)|(apps/admin/(.*/)?__tests__/.*))$'
readonly MAXIM_IMPACT_RULE_19_INCLUDE_REGEX='^((infra/certs/.*))$'
readonly MAXIM_IMPACT_RULE_20_INCLUDE_REGEX='^((infra/docker-compose\.yml))$'
readonly MAXIM_IMPACT_RULE_21_INCLUDE_REGEX='^((infra/docker-compose\.local\.yml)|(infra/docker-compose\.scale\.yml))$'
readonly MAXIM_IMPACT_RULE_22_INCLUDE_REGEX='^((infra/nginx/major-maksimov\.ru\.conf)|(infra/www/major-maksimov/.*))$'
readonly MAXIM_IMPACT_RULE_23_INCLUDE_REGEX='^((infra/nginx/admin\.major-maksimov\.ru\.conf))$'
readonly MAXIM_IMPACT_RULE_24_INCLUDE_REGEX='^((infra/nginx/maxim\.play-team\.ru\.conf))$'
readonly MAXIM_IMPACT_RULE_25_INCLUDE_REGEX='^((infra/vk-proxy/.*))$'
readonly MAXIM_IMPACT_RULE_26_INCLUDE_REGEX='^((infra/nginx/.*))$'
readonly MAXIM_IMPACT_RULE_26_EXCLUDE_REGEX='^((infra/nginx/major-maksimov\.ru\.conf)|(infra/nginx/admin\.major-maksimov\.ru\.conf)|(infra/nginx/maxim\.play-team\.ru\.conf))$'
readonly MAXIM_IMPACT_RULE_27_INCLUDE_REGEX='^((infra/scripts/.*))$'
readonly MAXIM_IMPACT_RULE_28_INCLUDE_REGEX='^((infra/.*))$'
readonly MAXIM_IMPACT_RULE_28_EXCLUDE_REGEX='^((infra/certs/.*)|(infra/docker-compose\.yml)|(infra/docker-compose\.local\.yml)|(infra/docker-compose\.scale\.yml)|(infra/env/.*)|(infra/nginx/.*)|(infra/scripts/.*)|(infra/vk-proxy/.*)|(infra/www/major-maksimov/.*))$'

maxim_impact_classify_path() {
  local path="${1:-}"
  path="${path#./}"
  while [[ "$path" == /* ]]; do path="${path#/}"; done
  while [[ -n "$path" && "$path" == */ ]]; do path="${path%/}"; done

  MAXIM_IMPACT_PATH_CLASSIFIED=0
  MAXIM_IMPACT_PATH_UNKNOWN=0
  MAXIM_IMPACT_PATH_API_SHARED=0
  MAXIM_IMPACT_PATH_MINIAPP_MAJOR_STATIC=0
  MAXIM_IMPACT_PATH_ADMIN_STATIC=0

  if [[ "$path" =~ $MAXIM_IMPACT_RULE_0_INCLUDE_REGEX ]]; then
    MAXIM_IMPACT_PATH_CLASSIFIED=1
  fi
  if [[ "$path" =~ $MAXIM_IMPACT_RULE_1_INCLUDE_REGEX ]]; then
    MAXIM_IMPACT_PATH_CLASSIFIED=1
  fi
  if [[ "$path" =~ $MAXIM_IMPACT_RULE_2_INCLUDE_REGEX ]]; then
    MAXIM_IMPACT_PATH_CLASSIFIED=1
  fi
  if [[ "$path" =~ $MAXIM_IMPACT_RULE_3_INCLUDE_REGEX ]] && ! [[ "$path" =~ $MAXIM_IMPACT_RULE_3_EXCLUDE_REGEX ]]; then
    MAXIM_IMPACT_PATH_CLASSIFIED=1
  fi
  if [[ "$path" =~ $MAXIM_IMPACT_RULE_4_INCLUDE_REGEX ]]; then
    MAXIM_IMPACT_PATH_CLASSIFIED=1
    MAXIM_IMPACT_PATH_API_SHARED=1
    MAXIM_IMPACT_PATH_MINIAPP_MAJOR_STATIC=1
    MAXIM_IMPACT_PATH_ADMIN_STATIC=1
  fi
  if [[ "$path" =~ $MAXIM_IMPACT_RULE_5_INCLUDE_REGEX ]]; then
    MAXIM_IMPACT_PATH_CLASSIFIED=1
    MAXIM_IMPACT_PATH_API_SHARED=1
    MAXIM_IMPACT_PATH_MINIAPP_MAJOR_STATIC=1
    MAXIM_IMPACT_PATH_ADMIN_STATIC=1
  fi
  if [[ "$path" =~ $MAXIM_IMPACT_RULE_6_INCLUDE_REGEX ]]; then
    MAXIM_IMPACT_PATH_CLASSIFIED=1
  fi
  if [[ "$path" =~ $MAXIM_IMPACT_RULE_7_INCLUDE_REGEX ]]; then
    MAXIM_IMPACT_PATH_CLASSIFIED=1
    MAXIM_IMPACT_PATH_MINIAPP_MAJOR_STATIC=1
  fi
  if [[ "$path" =~ $MAXIM_IMPACT_RULE_8_INCLUDE_REGEX ]]; then
    MAXIM_IMPACT_PATH_CLASSIFIED=1
  fi
  if [[ "$path" =~ $MAXIM_IMPACT_RULE_9_INCLUDE_REGEX ]] && ! [[ "$path" =~ $MAXIM_IMPACT_RULE_9_EXCLUDE_REGEX ]]; then
    MAXIM_IMPACT_PATH_CLASSIFIED=1
    MAXIM_IMPACT_PATH_API_SHARED=1
    MAXIM_IMPACT_PATH_MINIAPP_MAJOR_STATIC=1
    MAXIM_IMPACT_PATH_ADMIN_STATIC=1
  fi
  if [[ "$path" =~ $MAXIM_IMPACT_RULE_10_INCLUDE_REGEX ]]; then
    MAXIM_IMPACT_PATH_CLASSIFIED=1
  fi
  if [[ "$path" =~ $MAXIM_IMPACT_RULE_11_INCLUDE_REGEX ]]; then
    MAXIM_IMPACT_PATH_CLASSIFIED=1
    MAXIM_IMPACT_PATH_API_SHARED=1
  fi
  if [[ "$path" =~ $MAXIM_IMPACT_RULE_12_INCLUDE_REGEX ]]; then
    MAXIM_IMPACT_PATH_CLASSIFIED=1
    MAXIM_IMPACT_PATH_API_SHARED=1
  fi
  if [[ "$path" =~ $MAXIM_IMPACT_RULE_13_INCLUDE_REGEX ]]; then
    MAXIM_IMPACT_PATH_CLASSIFIED=1
    MAXIM_IMPACT_PATH_API_SHARED=1
  fi
  if [[ "$path" =~ $MAXIM_IMPACT_RULE_14_INCLUDE_REGEX ]] && ! [[ "$path" =~ $MAXIM_IMPACT_RULE_14_EXCLUDE_REGEX ]]; then
    MAXIM_IMPACT_PATH_CLASSIFIED=1
    MAXIM_IMPACT_PATH_API_SHARED=1
  fi
  if [[ "$path" =~ $MAXIM_IMPACT_RULE_15_INCLUDE_REGEX ]]; then
    MAXIM_IMPACT_PATH_CLASSIFIED=1
  fi
  if [[ "$path" =~ $MAXIM_IMPACT_RULE_16_INCLUDE_REGEX ]] && ! [[ "$path" =~ $MAXIM_IMPACT_RULE_16_EXCLUDE_REGEX ]]; then
    MAXIM_IMPACT_PATH_CLASSIFIED=1
    MAXIM_IMPACT_PATH_MINIAPP_MAJOR_STATIC=1
  fi
  if [[ "$path" =~ $MAXIM_IMPACT_RULE_17_INCLUDE_REGEX ]]; then
    MAXIM_IMPACT_PATH_CLASSIFIED=1
  fi
  if [[ "$path" =~ $MAXIM_IMPACT_RULE_18_INCLUDE_REGEX ]] && ! [[ "$path" =~ $MAXIM_IMPACT_RULE_18_EXCLUDE_REGEX ]]; then
    MAXIM_IMPACT_PATH_CLASSIFIED=1
    MAXIM_IMPACT_PATH_ADMIN_STATIC=1
  fi
  if [[ "$path" =~ $MAXIM_IMPACT_RULE_19_INCLUDE_REGEX ]]; then
    MAXIM_IMPACT_PATH_CLASSIFIED=1
    MAXIM_IMPACT_PATH_API_SHARED=1
  fi
  if [[ "$path" =~ $MAXIM_IMPACT_RULE_20_INCLUDE_REGEX ]]; then
    MAXIM_IMPACT_PATH_CLASSIFIED=1
    MAXIM_IMPACT_PATH_API_SHARED=1
    MAXIM_IMPACT_PATH_MINIAPP_MAJOR_STATIC=1
    MAXIM_IMPACT_PATH_ADMIN_STATIC=1
  fi
  if [[ "$path" =~ $MAXIM_IMPACT_RULE_21_INCLUDE_REGEX ]]; then
    MAXIM_IMPACT_PATH_CLASSIFIED=1
  fi
  if [[ "$path" =~ $MAXIM_IMPACT_RULE_22_INCLUDE_REGEX ]]; then
    MAXIM_IMPACT_PATH_CLASSIFIED=1
  fi
  if [[ "$path" =~ $MAXIM_IMPACT_RULE_23_INCLUDE_REGEX ]]; then
    MAXIM_IMPACT_PATH_CLASSIFIED=1
  fi
  if [[ "$path" =~ $MAXIM_IMPACT_RULE_24_INCLUDE_REGEX ]]; then
    MAXIM_IMPACT_PATH_CLASSIFIED=1
  fi
  if [[ "$path" =~ $MAXIM_IMPACT_RULE_25_INCLUDE_REGEX ]]; then
    MAXIM_IMPACT_PATH_CLASSIFIED=1
  fi
  if [[ "$path" =~ $MAXIM_IMPACT_RULE_26_INCLUDE_REGEX ]] && ! [[ "$path" =~ $MAXIM_IMPACT_RULE_26_EXCLUDE_REGEX ]]; then
    MAXIM_IMPACT_PATH_CLASSIFIED=1
  fi
  if [[ "$path" =~ $MAXIM_IMPACT_RULE_27_INCLUDE_REGEX ]]; then
    MAXIM_IMPACT_PATH_CLASSIFIED=1
  fi
  if [[ "$path" =~ $MAXIM_IMPACT_RULE_28_INCLUDE_REGEX ]] && ! [[ "$path" =~ $MAXIM_IMPACT_RULE_28_EXCLUDE_REGEX ]]; then
    MAXIM_IMPACT_PATH_CLASSIFIED=1
  fi

  if [[ "$MAXIM_IMPACT_PATH_CLASSIFIED" -eq 0 ]]; then
    MAXIM_IMPACT_PATH_UNKNOWN=1
    MAXIM_IMPACT_PATH_API_SHARED=1
    MAXIM_IMPACT_PATH_MINIAPP_MAJOR_STATIC=1
    MAXIM_IMPACT_PATH_ADMIN_STATIC=1
  fi
}
