ALTER TABLE "chat_rules"
  ADD COLUMN IF NOT EXISTS "button_enabled" BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS "button_url" TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS "button_text" TEXT NOT NULL DEFAULT 'Открыть';
