export const APP_ICON_NAMES = [
  'Book',
  'Bookmark',
  'ChatLines',
  'Check',
  'CheckSquare',
  'Community',
  'Copy',
  'FilterList',
  'Flask',
  'Gift',
  'Group',
  'Hashtag',
  'Link',
  'Megaphone',
  'MoonSat',
  'NavArrowLeft',
  'NavArrowRight',
  'Phone',
  'PlusCircle',
  'RefreshDouble',
  'Reports',
  'Search',
  'SendDiagonal',
  'Settings',
  'ShieldAlert',
  'ShieldCheck',
  'Shop',
  'Sparks',
  'Star',
  'StatsUpSquare',
  'Terminal',
  'UserPlus',
  'WarningTriangle',
  'Wrench',
  'Xmark',
] as const;

export type AppIconName = (typeof APP_ICON_NAMES)[number];
