// FLAG: Every SQL inventory traversal uses the literal primary key of a reviewed table.
// A finite exhausted page is proof; hitting any shared budget is a refusal, not an empty result.
export const LEGACY_RECOVERY_SQL_PRIMARY_KEYS = Object.freeze({
  webhook_events: ['id'],
  webhook_execution_claims: ['id'],
  max_action_ledger: ['id'],
  moderation_delete_intents: ['id'],
  moderation_delete_intent_reasons: ['id'],
  moderation_rule_followups: ['id'],
  night_mode_transition_reconcile_requests: ['chat_id'],
  night_mode_transition_scheduled_jobs: ['chat_id', 'job_id'],
  message_retention_candidates: ['chat_id', 'message_id'],
  message_retention_policies: ['chat_id'],
  publisher_entity_bindings: ['chat_id'],
  publisher_access_refresh_obligations: [
    'publisher_bot_id',
    'chat_id',
    'proof_checked_at',
    'required_before',
  ],
  managed_entity_access_edges: ['chat_id', 'user_id', 'bot_id'],
  managed_entity_handshake_outcomes: ['chat_id', 'user_id', 'bot_id'],
  publisher_start_intents: ['id'],
  chat_auto_comment_attach_markers: ['id'],
  channel_auto_post_attach_markers: ['id'],
  publisher_auto_reply_deliveries: ['id'],
  publisher_auto_reply_asset_uploads: ['id'],
  publisher_post_import_sessions: ['id'],
  publisher_auto_reply_authoring_sessions: ['id'],
  publisher_auto_reply_authoring_messages: ['id'],
  publisher_private_flow_leases: ['publisher_bot_id', 'actor_user_id'],
  publisher_comment_notification_events: ['id'],
  publisher_comment_notification_deliveries: ['id'],
  audit_logs: ['id'],
  channel_suggestion_admin_deliveries: ['id'],
  publications: ['id'],
  publication_assets: ['id'],
  publication_schedules: ['id'],
  publication_occurrences: ['id'],
  managed_broadcasts: ['id'],
  managed_broadcast_occurrences: ['id'],
  managed_broadcast_deliveries: ['id'],
  managed_autopost_materializations: ['id'],
  managed_autopost_rules: ['id'],
  suggestion_subscription_watches: ['id'],
  suggestion_subscription_publications: ['id'],
  vk_parsing_sources: ['id'],
  vk_parsing_posts: ['id'],
  vk_bot_reviews: ['id'],
  vk_bot_review_inboxes: ['bot_id', 'user_id'],
  vk_parsing_media_cache: ['id'],
  managed_polls: ['id'],
  managed_giveaways: ['id'],
  managed_giveaway_winners: ['id'],
  managed_giveaway_winner_notifications: ['id'],
} as const);
