// FLAG: This literal catalog names review surfaces only. It grants no authority
// to install dispositions, suppress commands, start workers or replay effects.
export const LEGACY_RECOVERY_LIVE_QUEUE_NAMES = Object.freeze([
  'moderation',
  'moderation-critical',
  'moderation-background',
  'moderation-default',
  'moderation-join-0',
  'moderation-join-1',
  'moderation-join-2',
  'moderation-join-3',
  'moderation-default-0',
  'moderation-default-1',
  'moderation-default-2',
  'moderation-default-3',
  'moderation-default-4',
  'moderation-default-5',
  'moderation-default-6',
  'moderation-default-7',
  'moderation-default-8',
  'moderation-default-9',
  'moderation-default-10',
  'moderation-default-11',
  'moderation-default-12',
  'moderation-default-13',
  'moderation-default-14',
  'moderation-default-15',
  'moderation-actions',
  'max-actions-critical',
  'max-actions-interactive',
  'max-actions-background',
  'max-chat-admin-roster-sync',
  'moderation-delete-intents',
  'night-mode-transitions',
  'global-spammer-denorm',
  'commercial-image-ocr',
  'message-duplicates',
  'photo-duplicates',
  'publisher-binding-refresh',
  'publisher-chat-comments',
  'publisher-post-import',
  'publisher-auto-replies',
  'publisher-auto-reply-authoring',
  'publisher-suggestion-admin',
  'publisher-start',
  'publisher-video-upload',
  'publisher-suggestion-publication',
  'publisher-publication-wakeup',
  'vk-parsing-sync',
  'vk-parsing-publisher',
  'marketplace-publisher-access',
  'admin-managed-entities-refresh',
  'admin-manual-fanout',
  'admin-super-ban',
  'admin-suggestion-delivery',
  'message-retention',
] as const);

export const LEGACY_RECOVERY_LIVE_QUEUE_STATES = Object.freeze([
  'wait',
  'paused',
  'active',
  'delayed',
  'prioritized',
  'waiting-children',
  'failed',
  'completed',
] as const);
